### ISSUE TITLE
10 weights in the repo, one looks repeated

### ISSUE THREAD

**Issue by FdezRomero** [JulietaUla/Montserrat#1]
Hello @JulietaUla and @juandelperal!

First of all, thank you for your great Montserrat font :+1: One of the biggest issues I had initially was that it was only available in 2 weights in Google Fonts, but last year I discovered the Thin and Light weights and I loved them. I now see that you have been working in all the 9 weights (yaaay!) but when I downloaded this repo I found there are actually 10 weights :confused:

I noticed that the **Hairline** and **Thin** weights are almost identical, but the font height seems to be different. I assume one of them is repeated. **Which one is the right one?**

Thanks a lot,
Regards from Madrid

**Comment by juandelperal** [comment]
Gracias por avisar! Ya borramos hairline.
Saludos desde Argentina

**Comment by FdezRomero** [comment]
Gracias Juan! :wink:

**Comment by JulietaUla** [comment]
Genial!!!!
Gracias Juan, Gracias Rodrigo!
Besos
Julieta

2015-06-02 9:28 GMT-03:00 Rodrigo Fernández Romero <notifications@github.com
