### ISSUE TITLE
Minor outline issue in glyph 'W'

### ISSUE THREAD

**Issue by kalapi** [JulietaUla/Montserrat#10]
The horizontal segment on the top of the centre 'apex' of the glyph is not perfectly flat.

**Masters Affected**: Black, and Regular

Reference:
![screen shot 2016-05-13 at 02 13 10](https://cloud.githubusercontent.com/assets/15804460/15229815/488bbc82-18b0-11e6-8d33-1790cc65646b.png)
![screen shot 2016-05-13 at 02 13 17](https://cloud.githubusercontent.com/assets/15804460/15229824/4fba734a-18b0-11e6-9ae0-b1e0b90bdd32.png)

**Comment by juandelperal** [comment]
Thanks @kalapi 
And yes, you can modify the fonts and make a pull request
