### ISSUE TITLE
TTF version of 3.100?

### ISSUE THREAD

**Issue by trlpath** [JulietaUla/Montserrat#103]
Hi I am looking for ttf files for version 3.100/3.001 - as I am trying to use documents that were made using the OTF versions, and the name and weight changes post version 3 etc mean that I can't use later font versions - and the software I need to use only works with TTF fonts. Are TTF fonts available?

**Comment by alerque** [comment]
You should be able to find those files in the git history. First look through commits and find a point before the new metrics were introduced, then browse the repository files at that point.

**Comment by trlpath** [comment]
Thanks, I have tried, but can only find OTF versions of 3.100 - might have found them elsewhere, which is not ideal but may have to do. Appreciate you taking the time to respond though.

**Comment by alerque** [comment]
@trlpath Try looking in the git history for the Google [fonts repo](https://github.com/google/fonts), sadly there are many font "releases" that turn up in there that were never posted to upstream projects. If not, there are lots of ways to convert OTF to TTF that are _mostly_ usable.

I have to say though it's pretty weird that you have documents made with the legacy OTF fonts but can only process them if you find a TTF version! It sounds like you need a new tool chain friend ;-)
