### ISSUE TITLE
Error in Montserrat.css

### ISSUE THREAD

**Issue by TonyStachnicki** [JulietaUla/Montserrat#107]
There is an error in the Montserrat.css file.
The @font-face rule for 'Montserrat Alternates Black-Italic' specifies the font-family as 'Montserrat'.
I think it should be 'Montserrat Alternates'.

It's the final rule in the file.

Apart from that, beautiful fonts.

**Comment by limburgher** [comment]
This seems to be causing an issue with Inkscape:
Warning: Font face with same CSS values already added: Montserrat Light (Light, Light)
Warning: Font face with same CSS values already added: Montserrat Normal (Regular, Regular)
Warning: Font face with same CSS values already added: Montserrat Bold (Bold, Bold)
Warning: Font face with same CSS values already added: Montserrat Ultra-Bold (ExtraBold, ExtraBold)
Warning: Font face with same CSS values already added: Montserrat Italic (Italic, Italic)
https://bugzilla.redhat.com/show_bug.cgi?id=1974044

**Comment by juandelperal** [comment]
Thanks for reporting the issue
In our next release we will delete the css file as it doesn't make much sense considering the possibility to use the variable font in the first place.
