### ISSUE TITLE
iOS 14 and Montserrat by GoggleFonts

### ISSUE THREAD

**Issue by c00lib1n** [JulietaUla/Montserrat#109]
Cyrrilic letters drawed by latin symbol after iOS14 update 
https://fonts.google.com/specimen/Montserrat
Test words: "Алая вспышка осветила силуэт зазубренного крыла." 
'**k**' symbol must be '**к**' '**ш**' '**л**' '**в**' and another - taken from latin.

![photo_2020-09-18_17-28-16](https://user-images.githubusercontent.com/8288296/93610016-2c038580-f9d5-11ea-8588-55b69157ecc2.jpg)

Also "Montserrat Alternates"  and some another fonts have this trouble.

**Comment by alerque** [comment]
I can say with some confidence that this is not a problem with the font, but a bug in either iOS 14 or the Google Fonts API that dishes out modified versions of fonts and stylesheets.

I see in your screenshot that Raleway is doing the same thing. As one of the current maintainers of that font I checked both it and Montserrat, and all is well:

![image](https://user-images.githubusercontent.com/173595/93612873-c2857600-f9d8-11ea-96a1-7d3cbacc3e34.png)

You should report this to the [Google Fonts](https://github.com/google/fonts/) repository issue tracker and/or whatever mechanism Apple gives you for your devices. This is not something individual font projects are responsible for, at least the two fonts in your list I know about are both fine.

**Comment by alerque** [comment]
This issue here can be closed.

**Comment by gigantz** [comment]
@c00lib1n,
To fix this bug, add this into your global style file
```css
html {
  -webkit-locale: auto;
}
```
