### ISSUE TITLE
Family name should be "Montserrat" in otf and woff files

### ISSUE THREAD

**Issue by paya-cz** [JulietaUla/Montserrat#11]
When I use [FontForge](https://fontforge.github.io/en-US/) to open [Montserrat Light](https://github.com/JulietaUla/Montserrat/blob/master/otf/Montserrat-Light.otf), I noticed the family name is set to "Montserrat Light" instead of just "Montserrat". Same applies to woff files as well as all the other font weights (not just Light).

In the app, I can see the incorrectly set "Montserrat Light" font family in:
Element -> Font Info -> PS Names
Element -> Font Info -> TTF Names

**Comment by davelab6** [comment]
Please see family naming spreadsheet in
http://designwithfontforge.com/en-US/Font_Info_&_Metadata.html

**Comment by paya-cz** [comment]
Do you please know if these metadata embedded in the font file have any effect in old/modern web browsers when used in the @font-face CSS rule, where I override "font-family" to be uniform as "Montserrat"?

**Comment by paya-cz** [comment]
Ah found the [answer](http://tympanus.net/codrops/css_reference/font-face/) myself. To quote (when referring to font-family property):

> This descriptor defines the font family name that will be used in all CSS font family name matchings. It is required for the @font-face rule to be valid. It overrides the font family names contained in the underlying font data.

Sorry for this thread. :-)
