### ISSUE TITLE
Greek glyphs weights not equivalent

### ISSUE THREAD

**Issue by Mereo4** [JulietaUla/Montserrat#110]
Hello, working with Greek translations, we found that the Greek glyphs are actually bolder than the Latin ones at equal weights.

Here is a short example:
<img width="288" alt="montserrat-greek-weight-diff" src="https://user-images.githubusercontent.com/51989963/108716994-0f87ee00-751d-11eb-8095-85d63e1f16ef.png">

We are using the fonts from your repo, v7.210.

**Comment by davelab6** [comment]
Montserrat doesn't support Greek. 

https://fonts.google.com/specimen/Montserrat?preview.text_type=custom&preview.text=Greek%20%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC

<img width="686" alt="Screen Shot 2021-02-22 at 10 10 43" src="https://user-images.githubusercontent.com/261579/108727163-3ed73480-74f6-11eb-8873-cfe15f4c4434.png">

**Comment by solmatas** [comment]
But, it CAN support Greek if you are interested! ;)
@juandelperal @JulietaUla

**Comment by Mereo4** [comment]
Oh well, thank you, I didn't know. And as the issue remains, the screenshot I actually provided was related to another font, sorry.

@solmatas So it means you could implement this in a future release?

**Comment by solmatas** [comment]
@Mereo4 We have experience developing Greek fonts, so if anyone here is interested in supporting our work, we can have a chat.

**Comment by Mereo4** [comment]
In this case, I'm just a developer passing by for what happened to be wrong reasons, so I will simply close this issue. Thanks. ;-)

**Comment by juandelperal** [comment]
@Mereo4 
You can try https://www.fauxfoundry.com/
It's not the same as using a font with real greek support, but a good fallback

**Comment by Mereo4** [comment]
@juandelperal 
That's really interesting, thank you for the link.

**Comment by ipassas** [comment]
> But, it CAN support Greek if you are interested! ;)
> @juandelperal @JulietaUla

count me in as well

**Comment by AndreasZorpidis** [comment]
Posting this here too since it might be helpful to some of you.

I needed basic Greek support with a couple more weights (especially a variable version based on the latest v8.000 from Google Fonts) so I decided to give it a try and remix it using glyphs from the font itself. You can find it [here](https://github.com/AndreasZorpidis/Montserrat-Z-Remix).

Notice: I also modified the letters "π" in Greek and "a" in Latin.

Hope that helps :)
