### ISSUE TITLE
₿ - Bitcoin symbol (U+20BF)

### ISSUE THREAD

**Issue by sohomang** [JulietaUla/Montserrat#115]
An increasing number of typefaces are adding support to the Bitcoin symbol 🌱 
Some fonts that support it in multiple weights: 
- Inter, https://github.com/rsms/inter/issues/284
- Apple's [SF font suite](https://developer.apple.com/fonts/)

Let me know how we can support your work!

**Comment by solmatas** [comment]
Hi there! 
thank you for the suggestion. 
We will add the Bitcoin symbol in the coming days.

**Comment by MY1L** [comment]
Hi (just passed by this issue), I have designed a version of Montserrat with ₿~
![2021-8-9 22-15-13](https://user-images.githubusercontent.com/58043328/128721980-a9677824-a596-4160-af6e-eed64dc11b57.png)
[Releases · MY1L/Monu](https://github.com/MY1L/QuQi/releases)

**Comment by juandelperal** [comment]
https://github.com/JulietaUla/Montserrat/releases/tag/v7.222
Thanks @sohomang
