### ISSUE TITLE
Montserrat font on Word for PC

### ISSUE THREAD

**Issue by GHtrueMA** [JulietaUla/Montserrat#119]
We have noticed an odd issue with the Montserrat font when used on Word for PC vs Mac

Any word that starts with the letter i is auto-capitalized even if it is the first letter of a word and not the individual letter I.  Any letter i is always uppercase from the moment you type it.

All of the other variants of the font don't seem to exhibit this behavior.  
Montserrat Black, Thin, Medium, etc.

You can sort of work around it by typing the 2nd letter or the word and then adding i in front of it or you can turn off the autocorrect i to I (this is not ideal).  

Is there anything special about the letter i in the that may cause Word to want to start off as uppercase or can this be fixed?

**Comment by juandelperal** [comment]
Hi @GHtrueMA 
This seems to be the auto-capitalization issue related to Word itself. If the letter was 
incorrectly mapped you would never see it (in any position of the word).
We are closing this issue, but let us know if the problem persists
