### ISSUE TITLE
Can we customize some letters for a logo?

### ISSUE THREAD

**Issue by elias-naffaa** [JulietaUla/Montserrat#120]
Hello There, thank you for this wonderful font.

I am using this font to create a logo for my company, is it okay if I changed a little in the letters' shapes, like extending some paths?

Thank you!

**Comment by alerque** [comment]
I don't think the license will matter if what you are releasing is just the logo you made with it. The logo you make can be used however. Only if you release the *font* you modified to anybody (even the customer) the OFL license has to follow the font itself, they need to know the modified font they get isn't "theirs" exclusively, it can and should be publicly available under the terms of the OFL.

Not a lawyer, just observing my understanding of font licenses vs. the things you make with them.
