### ISSUE TITLE
outlines/paths on Montserrat broken

### ISSUE THREAD

**Issue by geknz** [JulietaUla/Montserrat#124]
the Montserrat font seems to be set up differently - and for our use broken. We're using the font in a web project with an outline made in css by using:

```
-webkit-text-fill-color: transparent;
-webkit-text-stroke-width: 2px;
-webkit-text-stroke-color: inherit;
```

With an outline the letters now look like beeing different paths, rather than one path per letter:

after 12.01.21 (now)
![image](https://user-images.githubusercontent.com/97600080/149128070-a491481f-d7fa-49bc-8014-c6dbd3359c12.png)

before 12.01.21 (before)
![image](https://user-images.githubusercontent.com/97600080/149128269-70bc8a88-6f81-450c-8c0b-6e672fa01ab5.png)

whole webpage:
https://iq.space/

**Comment by MisterAwesome** [comment]
Can confirm. I have the same problem today.

`-webkit-text-stroke: 3px #fff;
    -webkit-text-fill-color: transparent;`

![image](https://user-images.githubusercontent.com/29097915/149188216-16d7431d-b959-4064-93e2-5bc141af9179.png)

**Comment by juandelperal** [comment]
Hi there,

In many cases, variable fonts need the contours to be drawn this way. This ensures a better interpolation of the shapes across the variations.
This is not something we can change. 
You can  either use the static versions (not variable fonts) or emulate a stroke using CSS shadow instead of `text-stroke`. Something like:

`text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000; `

**Comment by dangermendez** [comment]
But I found that even the static versions have the contour problems, see for yourself:
<img width="720" alt="Screen Shot 2022-02-08 at 6 18 19 PM" src="https://user-images.githubusercontent.com/88398714/153085246-80128fd0-383b-48e4-b84b-b25239f04092.png">
(contours circled)
(Using the Regular static file on Google Fonts' website)

**Comment by solmatas** [comment]
@dangermendez The static fonts (ttf and otf) in this repository don't have open shapes:   
 https://github.com/JulietaUla/Montserrat/blob/master/fonts/otf/Montserrat-Regular.otf

See the imagesbellow:
 
<img width="822" alt="Attf" src="https://user-images.githubusercontent.com/8105496/153201696-b04eb13d-bbe0-49fc-9760-5acabeebaa18.png">
<img width="822" alt="Aotf" src="https://user-images.githubusercontent.com/8105496/153201704-0772d6cc-6ac5-44d9-9237-89fc5358dba8.png">

You can download these fonts.

**Comment by dangermendez** [comment]
@solmatas Yeah, I know that the ones on this repository are from v7.222 which don't have the open shapes, the **static** ones from **fonts.google.com** (v8.000) **have** the open shapes as per the above photo.
