### ISSUE TITLE
inconsistency with Cyrillic

### ISSUE THREAD

**Issue by v-marinkov** [JulietaUla/Montserrat#128]
Hi, I noticed some strange behaviour with Cyrillic characters. When using the fonts in Windows, Mac or FontForge (both .ttf and .woff2) the phrase "предоставяне на интелигентни решения" looks like this:
![image](https://user-images.githubusercontent.com/7135724/158881975-4fe8790e-01c4-487e-a4cb-73628fbfafe8.png)
which to my eye is wrong.

When using the same font file on a website (.woff2) the phase looks correctly:
![image](https://user-images.githubusercontent.com/7135724/158882117-eb421f84-db17-4692-9eab-9a86f624b5b8.png)

When creating subsets of the font using https://everythingfonts.com/subsetter , the created font looks like the first example even in web browsers. Attached is an example of these subsets.
[Montserrat-problematic-subset.zip](https://github.com/JulietaUla/Montserrat/files/8290018/Montserrat-problematic-subset.zip)

Here is a working subset in web browsers but not in Windows:
[montserrat-working-subset.zip](https://github.com/JulietaUla/Montserrat/files/8290024/montserrat-working-subset.zip)

What could be going wrong and how can I get consistently Cyrillic like in the second sample on both desktop and web browsers? Again, I never managed to preview it correctly on Desktop or Google Fonts but in most cases it worked correctly in the browser.

Many thanks!

**Comment by v-marinkov** [comment]
It turns out Bulgarian has it's own glyph version of some Cyrillic characters. I, for one, had no idea. Desktop font viewers apparently use the default Cyrillic version while web browsers load the Bulgarian when lang="bg".

**Comment by FlaviusChromacitrin** [comment]
![Image](https://github.com/user-attachments/assets/82bff3ae-8b45-40a3-b662-e80345185cac)
Will work completely fine on NeaMonternaFont B. The B is the Bulgarian modifier
