### ISSUE TITLE
MontserratAlternates.glyphs

### ISSUE THREAD

**Issue by graphicore** [JulietaUla/Montserrat#13]
Hi Julieta,

I'm wondering about how you use the MontserratAlternates.glyphs file. It looks like it's the same as Montserrat.glyphs with the ss01 feauture turned on. If so, and if there's no other variation I wonder if we could use Adam Twardochs [pyftfeatfreeze](https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze) to produce an equivalent result. The advantage of that approach would be that there would be just on source file to maintain.

Best, Lasse

**Comment by davelab6** [comment]
Glyphs has a custom parameter to do this

**Comment by juandelperal** [comment]
Thanks @graphicore I will try to set the custom parameters so it can be done in directly in Glyphs. Thanks @davelab6 for the suggestion
