### ISSUE TITLE
Problem on printing in print shop

### ISSUE THREAD

**Issue by brunnew** [JulietaUla/Montserrat#131]
I work on print shop, using xerox, konica and other printers, and our clients send files to us for print. Now some clients send files using montserrat font, and print result as the same as related problem with outline on websites and google documents  related by other users here on topics. 

I try to make a test, in illustrator CS6 with a static font, i created a stroke text and i see the same problem, i believe is a font problem, not a printer and not a software. Solution at the moment is convert fonts to outline using enfocus pitstop, but is expensive to our time make this for all jobs or try to search in each job if have a montserrat or not.

**Comment by juandelperal** [comment]
Hi @brunnew 

Sorry for the long delay in answering this issue. Do you have any images showing the error?
If this relates to problems with overlapping contours, have you tried using static fonts instead of the variable format?
