### ISSUE TITLE
Is it possible to more "accurately" draw the letters?

### ISSUE THREAD

**Issue by Li-Deheng** [JulietaUla/Montserrat#133]
👋🏻 Hi Julieta
It is noticeable that many letters have been drawn as separate parts or with extra inner lines.  This happens when use **"stroke"** in After Effects and many other programs.
<img width="660" alt="20221115130941" src="https://user-images.githubusercontent.com/48417413/204155350-5b29a40e-352c-477f-93d3-78790b45cabc.png">
I don't know what program you used when creating the font, but I tried "Glyphs 3" and "Adobe Illustrator" to fix all the problems, but I think this is your product and it would be better if you yourself would fix and make a more accurate font. 

Can you fix and officially post a neater version on "Google Fonts"?

**Comment by kenmcd** [comment]
Use the v7.222 release from this repository. 
They have the overlaps removed.

**Comment by Li-Deheng** [comment]
I would like the latest versions with improvements to this font to be posted on "Google Fonts" as well.

**Comment by kenmcd** [comment]
> I would like the latest versions with improvements to this font to be posted on "Google Fonts" as well.

Not going to happen.
When Google Fonts builds the fonts using their tools they leave the ovelaps in.
Their position is that the applications should handle this correctly.

Issues with Google Fonts should be posted in their repository not here.
The developer here has no control over what Google Fonts does.

**Comment by juandelperal** [comment]
Hi @Li-Deheng 

This is a known issue related to how variable fonts need to be drawn to better interpolation. More details and possible workarounds here: 
https://github.com/JulietaUla/Montserrat/issues/124#issuecomment-1011997636
