### ISSUE TITLE
Problem with Montserrat-VariableFont_wght.ttf on Google Chrome Version 109.0.5414.75 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by ToomasMolder** [JulietaUla/Montserrat#134]
OS Microsoft Windows Version 21H2 (OS build 19044.2364)
Browser Google Chrome Version 109.0.5414.75 (Official Build) (64-bit)
Font Montserrat-VariableFont_wght.ttf

Sample webpage https://www.eucybernet.eu/

Screenshots with Montserrat-VariableFont_wght.ttf installed:
![yes_montserrat_2023-01-20 (2)](https://user-images.githubusercontent.com/17491091/213581582-b08a9f93-c6ba-4494-aebd-bb841e2bb42b.PNG)

Screenshots with Montserrat-VariableFont_wght.ttf NOT installed (uninstalled):
![no_montserrat_2023-01-20 (2)](https://user-images.githubusercontent.com/17491091/213581663-0d96bc58-d942-404f-b5ee-540d88f31ada.PNG)

Intended view with Montserrat-VariableFont_wght.ttf installed will be same/similar about bold, italic, visibility with those when NOT installed.
Problem still exists when Google Chrome Settings reset.
Problem still exists when Google Chrome in Incognito.

No problems found with older Google Chrome version.
No problems found with other browsers like Firefox (109.0 (64-bit)) or Vivaldi (5.6 for Windows).
No problems found with font Montserrat-Italic-VariableFont_wght.ttf

**Comment by kenmcd** [comment]
Appears to be a browser issue.
Should report browser issues in the browser bug tracker.
