### ISSUE TITLE
Add the already developed Montserrat Stencil font to collection?

### ISSUE THREAD

**Issue by teese** [JulietaUla/Montserrat#135]
I love the Montserrat font, and wish there was a stencil version.
I was hoping to use the stencil font to make 3D printed name-cards, similar to those designed by TheCapitalDesign and shared on [Thingiverse](https://www.thingiverse.com/thing:1713563).
I found a nice [blog post by Connie Worthington](http://typography.network/2020/06/15/cafod-emergency-response-team-stencil-font/) describing the creation of the Montserrat Stencil font, but it's not actually available to download and use.
Is it possible to add the stencil font to the collection?

**Comment by fitojb** [comment]
I think it is the job of that version’s creators to contribute their work via a PR

**Comment by juandelperal** [comment]
Hi @teese 

I agree with @fitojb. Maybe the authors can upload this project to Github as a fork or even as a new project.
The character set has changed lately so these changes might be already out of sync.

I'm closing this issue
