### ISSUE TITLE
Font weight is weird in firefox, if font loaded from google fonts

### ISSUE THREAD

**Issue by FragsterAt** [JulietaUla/Montserrat#136]
![изображение](https://user-images.githubusercontent.com/20900647/228524950-eb402e4b-4b0d-4ac5-aa36-6043503a6e7f.png)

If loaded from [fontsource](https://fontsource.org/fonts/montserrat), all is ok.

Please update google version, it is used by many sites.

**Comment by juandelperal** [comment]
Hi @FragsterAt 

Thanks for filling this issue. We are about to release a new version, I hope then this hinting issue is fixed.
Anyway, could you please provide more details about the device, browser, and the Operating System of this screenshot?
Thanks!

**Comment by FragsterAt** [comment]
@juandelperal main reason for this result is that os is win server 2012 and browser is firefox, and it does not support variable fonts in windows <= win10. And default weight of variable version of montserrat is to thin. I don't know, can it be fixed by changing the font or not.

Relative bug https://github.com/quasarframework/quasar/issues/15639 with workaround (i don know, how they do that)

**Comment by juandelperal** [comment]
Ah, ok, that makes sense. 
That OS was released 4 years before variable fonts format was introduced.
We will close this issue for now. Thanks
