### ISSUE TITLE
Montserrat Monospaced and Montserrat Serif Versions

### ISSUE THREAD

**Issue by TheGitMpeg** [JulietaUla/Montserrat#141]
Hello Julieta,
I'd like to have monospaced and serif versions of Montserrat font.
Can you design Montserrat Monospace and Montserrat Serif fonts please? If not, you can contact anyone else.
That's because I would like to use Montserrat Monospace for my NetBeans appearance and the console (Command Prompt) application, and Montserrat Serif for professional looking as Montserrat fonts have the same loooking.

I like your Montserrat fonts. Thank you.

**Comment by JulietaUla** [comment]
Thank you for your interest in Montserrat fonts! We appreciate your feedback and your request for Monospace and Serif versions. At the moment, these specific styles aren't available within the Montserrat family. However, if you're interested in commissioning these new styles, please feel free to reach out to us via email. We'd be happy to discuss the possibility further.

**Comment by JulietaUla** [comment]
Closed #141
