### ISSUE TITLE
Improve Navajo support features

### ISSUE THREAD

**Issue by moyogo** [JulietaUla/Montserrat#142]
The Navajo language orthography uses ą ę į ǫ for nasal vowels and ą́ ę́ į́ ǫ́ for high tone nasal vowels, and their uppercase ĄĘĮǪ Ą́Ę́Į́Ǫ́.

The Navajo language system substitution in the locl feature subsitutes `/Aogonek/Eogonek/Uogonek/aogonek/eogonek/uogonek` for `/Aogonek.loclNAV/Eogonek.loclNAV/Uogonek.loclNAV/aogonek.loclNAV/eogonek.loclNAV/uogonek.loclNAV`.
- [ ] The substitution for `/Uogonek.loclNAV/uogonek.loclNAV` are not needed in Navajo as the orthography doesn’t use ų ų́ Ų Ų́. Even if the substitution is not needed, it can remain. However for other languages that may use it or the others, it would be useful to have a stylistic set feature with the substitutions.
- [ ] The substitutions are inconsistent, `/Iogonek/iogonek/Oogonek/oogonek` are not substituted to have the `/Ogonekcomb.loclNAV/igonekcomb.loclNAV/Ogonekcomb.loclNAV/ogonekcomb.loclNAV`. Please add those additional loclNAV variants.
- [ ] The substitution for `/iogonek` when combined with a top accent is missing. The latest versions of Glyphsapp can add the automatic code when `/iogonek.dotless` is present. Unfortunately it doesn’t add a substitution when `/iogonek.dotless.loclNAV` is present, so that needs to be added manualy at this point. Please add `idotless+ogonekcomb=iogonek.dotless idotless.loclNAV+ogonekcomb.loclNAV=iogonek.dotless.loclNAV` (or better with a new `/ogonekcomb.i.loclNAV` narrow like `/ogonekcomb.i`), update the ccmp and locl features and add an extra locl feature block, after the automatic locl feature block, with `script latn; language NAV; lookup locl_latn_NAV { sub iogonek.dotless by iogonek.dotless.loclNAV; } locl_latn_NAV;`.

<img width="927" alt="Screenshot 2023-11-13 at 16 50 13" src="https://github.com/JulietaUla/Montserrat/assets/1923747/df88a479-a948-4b38-b622-f7f7625c9be0">
<img width="1010" alt="Screenshot 2023-11-13 at 16 49 51" src="https://github.com/JulietaUla/Montserrat/assets/1923747/76b825d9-bc9b-4e9f-88dd-cda2cb533c89">

**Comment by kenmcd** [comment]
@moyogo 
What applications can actually use the `loclNAV` ?
Could not find any way to demonstrate this in LibreOffice.
Except in those fonts which also include a stylistic set.
It is also possible to demo in applications with a Glyph Browser.
But how does someone actually write Navajo text with the `loclNAV` localization?
My apologizes as this is a bit off-topic, but I figured you are one of the few people who may actually know this.
Even the Navajo language info and teaching websites have nothing about this.
All my web searches have been fruitless.
Thanks.

**Comment by moyogo** [comment]
@kenmcd Modern browsers will apply the locl feature when the `lang="nav"` or `xml:lang="nav" attributes are used in HTML. For example https://nv.wikipedia.org/ or https://www.jw.org/nv/

**Comment by kenmcd** [comment]
> @kenmcd Modern browsers will apply the locl feature when the `lang="nav"` or `xml:lang="nav" attributes are used in HTML. For example https://nv.wikipedia.org/ or https://www.jw.org/nv/

Thanks for the info and links.
Have been trying to document fonts which support Navajo (on desktop).
Merriweather and Source Sans 3 also have stylistic sets.
Noto Sans and Noto Serif do not have stylistic sets.
So no desktop support in those fonts that I can figure-out.
Hmmm...maybe I'll fork them and add it.

Did not think about the browser support. Thanks!

**Comment by juandelperal** [comment]
I think that upcoming version 9.0 covers this. We are closing this issue, thanks!
