### ISSUE TITLE
Cyrllic interpolation issue

### ISSUE THREAD

**Issue by davelab6** [JulietaUla/Montserrat#143]
https://twitter.com/MrWanted225/status/1727352802668605482 reports some Cyrillic interpolation issues

>  this issue i saw on Montserrat/Montserrat Alternates (Version 9.000) Exported OTF/TTF,Webfonts WOFF/WOFF2 Files as well on Montserrat[wght] & MontserratAlternates[wght] Exported Files.

![image](https://github.com/JulietaUla/Montserrat/assets/261579/545129f6-dc7a-4938-a902-8bf8d1ae0b8e)

**Comment by juandelperal** [comment]
Thanks for reporting this. Version 9 is still unreleased. The sources are now fixed
