### ISSUE TITLE
SSA - CCMP (rendering made) non-unicode letter bugs

### ISSUE THREAD

**Issue by EbenSorkin** [JulietaUla/Montserrat#144]
### 1) Roman  - Cedilla: 

<img width="109" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/b005deb2-9ebc-4aba-a338-7b5ccb594938">
<img width="77" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/085bc415-90af-4fe4-b998-52afb86b80b4">
<img width="55" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/d81567a1-c6a5-4a07-ac2d-4d0ea6a11f97">
<img width="59" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/78dc255c-fcf4-4376-86f3-38358f456edd">

The bottom anchor is not being treated in the same way in the roman as it is in the Italic leading to the Acedilla Icedilla and Ocedilla and U cedilla ccmp made letters having a rendering problem in the Roman. The origin of the issue may be not in the letters but in the cedilla or the cedill.case if that's what's in your source.

### 2) Roman and Italic - **Missing double Macron** - U+035F - 

<img width="72" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/a11bec2c-1b71-4471-acb0-0fafd14bbbc0">

### 3) Roman and Italic - Missing CCMP Open Type code for **idotless with these diacritics: acutemacroncomb macrongravecomb**. 
If you know how to adjust this go ahead if it isn't clear please let me know and I'll look at it with you.

<img width="62" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/c8800a22-9778-48d0-8eb1-ed81850a1c38">
<img width="52" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/01a45aae-b320-45b6-bba3-5a1aa8582e01">

### 4) Roman and Italic - Anchor placement or missing anchor **lc letter p** 
The expected look is something like this 
<img width="186" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/3c567047-ddee-4964-95a8-0115dc26ccd6">

But we have  
<img width="42" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/aa0e10b8-8a0c-4226-b03c-72f01de7cc13">
<img width="48" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/56c6dffa-0ad6-44c8-aeed-1994140a523f">

### 5) Roman and Italic - **Eng** - two problems 
This still has the cap N form which makes me wonder if this is really the updated version I am testing. But also there is meant to be a top anchor 
<img width="319" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/d554ffdc-f12c-44ab-b395-79099d93e42f">
<img width="502" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/c141c293-8a37-4359-bf4d-5ea791bc2336">
The now default form is like this: 
<img width="150" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/6f671d61-ef39-47d1-88c3-3f1f9b55f846">

### 6) Italic Mturned
This letters needs a top Anchor like the Roman has
<img width="488" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/f608fbfb-df65-4a37-a185-d5821dc221b1">

### 7) Roman and Italic - There needs to be dotless versions of iistroke called istroke.dotless and custom ( not automatic ) open Type code to make the dot go away.
I am finding this is a problem in nearly all the projects. 
<img width="120" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/20697dac-502f-44ca-a6fc-e1c0845629a3">
<img width="125" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/b54df4ff-56aa-44a0-a5a5-5516f0b435de">
In case it isn't obvious this is the sort of thing we are aiming for,
<img width="576" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/40a04a92-1381-44c7-ac5f-c4c18be7b7df">

Please let me know if you need help wit the needed OT code.

### 8 & 9) Italic -  The letters Hturned and Omega-latin need a top anchors

<img width="325" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/86f22113-1ba8-4f75-b1b2-b6c0105e0d32">

### 10) tilde top anchor missing capital/case narrow version of tilde 

See 
<img width="129" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/ea25e78a-f01c-4ee9-86db-2806ea67b90c">
<img width="77" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/8337f205-ac3e-4d26-a11d-d494a501e1d9">
vs 
<img width="76" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/f8463dd1-1174-4ccd-a862-c2867b26d556">

### 10) Italic - Turned e seems to have a top anchor that the schwa is missing

<img width="290" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/b83c214c-66ea-4243-a0b1-296723d2b4c3">

### 11) Italic - ramshorn missing top anchor 
<img width="223" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/2f4a5bdc-74fb-4850-a8a3-11d1559235b6">

### 12) Roman and Italic - vhook needs to have the top anchor placed a little higher to avoid classes with diacritics
<img width="489" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/bf0c3d5d-28fb-4053-a2ce-f4c19e77c96d">
<img width="259" alt="image" src="https://github.com/JulietaUla/Montserrat/assets/2181213/ba5f258e-b3dc-42c4-823b-8f66d8064160">

These notes show the heavy weight but they seem to apply consistently across the weight axis which keeps things simpler.

**Comment by juandelperal** [comment]
Thanks Eben! Now all missing anchors are there in 9.0 unmerged branch
