### ISSUE TITLE
Missing case swapping forms

### ISSUE THREAD

**Issue by m4rc1e** [JulietaUla/Montserrat#147]
The font has the following glyphs that are missing their case swapping forms:

U+0280: LATIN LETTER SMALL CAPITAL R
U+04C6: CYRILLIC SMALL LETTER EL WITH TAIL

We need to add:
U+01A6: LATIN LETTER YR  
 U+04C5: CYRILLIC CAPITAL LETTER EL WITH TAIL

@juandelperal once this is added, I think we're good.

**Comment by solmatas** [comment]
Hi Marc,

I added those glyphs and made a few changes.

**Comment by m4rc1e** [comment]
Fabulous. Thank you very much!
