### ISSUE TITLE
Fixes needed in order to release v9.0

### ISSUE THREAD

**Issue by m4rc1e** [JulietaUla/Montserrat#152]
I made a PR to google/fonts last week and Emma kindly did a review. She found a few things we need to fix before we can release, https://github.com/google/fonts/pull/8281#issuecomment-2402303242.

Please ignore the Indd rendering bug for now. It only occurs on this platform and I can't find a suitable fix atm. If users would like to use the family on Indesign, they can just use the supplied static fonts.

cc @juandelperal

**Comment by juandelperal** [comment]
Thanks Marc, we are on it.

**Comment by juandelperal** [comment]
I will close this issue to follow the conversation in google/fonts
