### ISSUE TITLE
Merge back into master

### ISSUE THREAD

**Issue by graphicore** [JulietaUla/Montserrat#17]
Please take a look at: https://github.com/JulietaUla/Montserrat/network

There are unfortunately 4 commits in your master that happened without prior merging the work of @kalapi 
Unfortunately we cannot merge the branch of @kalapi (and mine) back into master, because of conflicts.

I added the vendorID and I fixed the z.alt glyph.

My branch builds on Kalapis: https://github.com/graphicore/Montserrat/tree/mastering and I prepared it to get the ttf fonts into google fonts.

We should somehow merge the branches, however, I think the best approach at this point is to redo the missing changes on top of my branch and force push it to master.

**Comment by juandelperal** [comment]
Thanks Lasse
It would be great if you can redo the missing changes in your branch and then make a Pull request.

**Comment by graphicore** [comment]
@juandelperal as I tried to explain, a pull request won't work because automatic merging is not possible. It seems even hard to come to a mergable version by hand. This is also a problem of the single file approach of Glyphs. Since the changes seem not to be that many, I suggest redoing them later.

**Comment by juandelperal** [comment]
Oh, I see
Sorry if this is a silly question but in this case the repo will loose all
the commit history?

2016-10-04 16:40 GMT-03:00 Lasse Fister <notifications@github.com>:

**Comment by graphicore** [comment]
No, just your last 4 commits will be lost, and I think I re-did most of the changes. I can help you getting this done.

**Comment by JulietaUla** [comment]
OK, great! Go ahead. Please let us know if you need something else for doing it.

**Comment by graphicore** [comment]
yeah, I think you need to do this, I can tell you how.

Are you using git from the commandline?

**Comment by juandelperal** [comment]
I do

**Comment by graphicore** [comment]
Ok, great. So the easiest thing to do would be a hard reset, followed by a forced push. Then I can make a PR from my branch. The problem with the forced push is that people who forked the master won't be able to update easily. For those, a hard reset like below followed by just a `git pull` will do.


Maybe we create a backup branch first, just in case we break things. This creates `master_backup` on github:

```
$ git push origin master:master_backup
```

Hard reset; the commit last commit both branches have in common is: 22c82cf6e

```
$ git reset --hard 22c82cf6e
```

Forced Push; rewrite history on the remote branch, this is not a nice thing to do, but in this case we need to.

```
$ git push -f
```


Now it should be straight forward to make a PR for my branch.

@green-s I've seen you fork in the network graph. This will make it incompatible to master (but it will stay compatible to master_backup).

**Comment by graphicore** [comment]
I just created #19 this should become compatible when the above is done.

**Comment by juandelperal** [comment]
Great! All done and your PR merged. Please tell me if all went OK. Thanks

**Comment by graphicore** [comment]
I think that's alright.
