### ISSUE TITLE
Montserrat variations on Google font

### ISSUE THREAD

**Issue by carlotrimarchi** [JulietaUla/Montserrat#2]
Hello,
do you have any plan to add to Google font any of the other Montserrat variations like Hairline, Light and so on?

**Comment by CGTS** [comment]
I haven't seen any updates to this. Are there any plans to push these up to google fonts?

**Comment by CGTS** [comment]
Are there any plans to upload additional weights to google fonts? This is a fantastic typeface and I would love to use it on an upcoming project, but would need the lighter faces.

Thanks for your effort on creating this. It looks great.

**Comment by runn1ng** [comment]
see

https://github.com/google/fonts/issues/86

and

https://github.com/google/fonts/issues/2

**Comment by JulietaUla** [comment]
Thank you!

2015-07-27 14:21 GMT-03:00 Karel Bílek <notifications@github.com>:

**Comment by windgazer** [comment]
Anything that can be done to push this? Can those of us eager to use `Montserrat Light` on a website poke somebody to make this font shine with all it's deserved glory on Google Fonts?
Or perhaps some other investment of time (i.e. updating docs) followed by a pull-request? Let us know :)

**Comment by runn1ng** [comment]
@windgazer poke Google here

https://github.com/google/fonts/issues/2

**Comment by windgazer** [comment]
I don't understand why this ticket is being closed. The last time anybody said anything about this on the google API, it's that "there's a few things Julieta needs to do first before they can go live". Nothing has changed on google's repo, the missing font-weights aren't live and anybody wondering why, is left in the dark :(

**Comment by juandelperal** [comment]
Hi @windgazer Thanks for your comment
You'r right. The problem still persist, but the correct place for this issue is the Google Fonts repo: google/fonts#2

Also in the sandbox there are some news.
https://fonts-dev.sandbox.google.com/fonts

Cheers

**Comment by windgazer** [comment]
@juandelperal Now that is great news! I hope it makes it to the live font-api soon!

**Comment by davelab6** [comment]
@juandelperal please edit your comment to remove that sandbox link, it isn't meant to be public.

**Comment by juandelperal** [comment]
@davelab6 done

**Comment by davelab6** [comment]
Thanks!! :)

**Comment by nateh777** [comment]
Any updates on this? I was curious about Semibold specifically.
