### ISSUE TITLE
Wrong glyph for letter Đđ

### ISSUE THREAD

**Issue by lazarljubenovic** [JulietaUla/Montserrat#20]
The Serbian letter Đ has misplaced dash; it should pass through the middle of the vertical line of letter D. The non-caps version is good.

In Montserrat:
![Đđ](https://cloud.githubusercontent.com/assets/7661457/19865814/0d6523ee-9f9e-11e6-8100-78b05a1bba6a.png)

Should be:
![image](https://cloud.githubusercontent.com/assets/7661457/19865909/7a164bf8-9f9e-11e6-9d31-24cf2320bdfd.png)

**Comment by JulietaUla** [comment]
Please download the fonts from this repo.

**Comment by lazarljubenovic** [comment]
Ah, sorry. Indeed, it's an outdated version from [FontSquirrel](https://www.fontsquirrel.com/fonts/montserrat).
