### ISSUE TITLE
MontserratAlternates-UltraLight.otf is not a valid font file

### ISSUE THREAD

**Issue by zayuim** [JulietaUla/Montserrat#21]
The file "MontserratAlternates-UltraLight.otf" appears to be corrupt because Windows 7 x64 isn't accepting it.

**Comment by graphicore** [comment]
@zayuim could you try again with the current files and confirm that #24 fixed this?

**Comment by zayuim** [comment]
There is no longer an UltraLight variant.

**Comment by m4rc1e** [comment]
yes,

UltraLight was renamed to ExtraLight. The issue you're reporting is common in UltraLight fonts. It is safer to rename

**Comment by juandelperal** [comment]
Thanks @m4rc1e for the clarification. Closing this

**Comment by zayuim** [comment]
Hey thanks everyone! The ExtraLight file is working, and the font is looking great as always.
