### ISSUE TITLE
Can't print with any iteration of the font

### ISSUE THREAD

**Issue by calebsurface** [JulietaUla/Montserrat#23]
I'm hoping this is a known issue or someone else has experienced this. We have a Ricoh copier that won't allow any of our Macs to print from Word, Pages, TextEdit, and the like whenever we use Montserrat as a font. From what I understand, these program send the font and text to the printer. It prints fine to this copier from Windows. It prints fine from high-end applications like Photoshop or InDesign. Just not regular word processors.

Here is the error that prints out:

```
ERROR: invalidfont
OFFENDING COMMAND: define font

STACK:

/Font
-dictionary-
/VHGQJC+Montserrat-Light
```

I've been wracking my brain trying to find some sort of solution for this, and I'm really hoping someone here has an idea of what is going on.

**Comment by juandelperal** [comment]
Thanks @calebsurface for pointing this.
@graphicore Lasse: any idea of this problems? Also https://github.com/JulietaUla/Montserrat/issues/21
Do we have to re-generate all the fonts?

**Comment by calebsurface** [comment]
I will also mention that it works for me on another small MFP we have here, just not our large Ricoh MP C4503 machine.

**Comment by graphicore** [comment]
cc @m4rc1e any Idea?

**Comment by graphicore** [comment]
@juandelperal yeah I think we should regenerate all fonts. I probably only did ttf files, because that's what is tested with fontbakery by us.

**Comment by m4rc1e** [comment]
I also recommend regenerating the fonts, this may fix #21.

I will compare the old fonts against the new and see if this is a recurring issue.

I'll file a pr for this asap.

**Comment by davelab6** [comment]
Thanks Marc!

**Comment by m4rc1e** [comment]
@calebsurface hey, since the pr has just been merged. Please delete the old fonts from your system, download the new version and retry.

Regards,
Marc

**Comment by calebsurface** [comment]
YES! It is now printing perfectly fine! I have been wracking my brain and so has our printer company over this. This being fixed literally saved us a ton of money.

We are a church and just paid for a design company to do a brand guide for us. Since Montserrat is free and very similar to Avenir, they gave us it as our house font.

Thanks so much for helping us out and fixing this!

**Comment by m4rc1e** [comment]
@calebsurface BOOM! thank you sir!

@davelab6 I'll send a new pr to fonts/google tomorrow

Have a nice weekend,
Marc

**Comment by JulietaUla** [comment]
@m4rc1e @graphicore @kalapi Now you have now rights to push to the repo. I think this will make the things easier to fix in the future

**Comment by paulskinner** [comment]
Hi, I seem to be having this issue with the latest release for the OTF version of Montserrat Regular. The TTF works fine.
