### ISSUE TITLE
Tittle (dot) on "i" and "j" are not the same size

### ISSUE THREAD

**Issue by GillesVermeulen** [JulietaUla/Montserrat#25]
In heavier versions of the Montserrat font (bold, black,...) the tittles (dots) on "i" and "j" are not the same size. Was this on purpose? The Google font version does not have this issue.

![monserrat_i_j](https://cloud.githubusercontent.com/assets/2512763/20395455/4c8e6038-ace3-11e6-8b33-031b5939600c.PNG)

**Comment by JulietaUla** [comment]
Thanks @GillesVermeulen
We are working on adding the italics and expanding the character set on the
dev branch. We have discovered some inconsistencies like this and will be
fixed on the next release.

2016-11-17 12:32 GMT-03:00 GillesVermeulen <notifications@github.com>:

**Comment by GillesVermeulen** [comment]
Thanks a lot for the great font and the fast reaction!

**Comment by JulietaUla** [comment]
:)

2016-11-21 6:35 GMT-03:00 GillesVermeulen <notifications@github.com>:

**Comment by davelab6** [comment]
@juandelperal @JulietaUla any change you could hotfix the latest roman-only release to fix this, so I could launch it very soon? :)

**Comment by CaroGiovagnoli** [comment]
Hi @davelab6 , do you want us to replace with the latest otf and glyphs version in the master branch?
We are working in a branch.

**Comment by davelab6** [comment]
Ideally I'd like a new release with ttf files that I can onboard to Google
Fonts, that is what @kalapi last made, except it doesn't have this issue

**Comment by davelab6** [comment]
@juandelperal thank you!! @m4rc1e please queue up a release of just the roman family today, ahead of Dosis and the other stuff in your queue

**Comment by davelab6** [comment]
@juandelperal ah i checked that commit and many OTFs are added and all the TTFs are removed (along with the WOFF/EOT files which are not needed anyway :) I suggest that @m4rc1e review the glyphs file and make some TTFs and then you can make a release in https://github.com/JulietaUla/Montserrat/releases with the TTFs he provides
