### ISSUE TITLE
Umlauts äöü ÄÖÜ are defective

### ISSUE THREAD

**Issue by d-mal** [JulietaUla/Montserrat#27]
![montserrataou](https://cloud.githubusercontent.com/assets/24476952/21050384/abfb7ac2-be1a-11e6-8875-42a20ad34e13.PNG)
I just downloaded the latest fonts (v4) and in Medium, SemiBold, Bold and ExtraBold weights, the dots of the Umlauts äöü and ÄÖÜ are too close to each other. The other weights look OK, but might be worth checking anyway. The issue seems to be the same with the TTF and OTF versions, and also with the "Montserrat Alternates".

**Comment by CaroGiovagnoli** [comment]
Closes #27

**Comment by d-mal** [comment]
Thank you - now these letters looks fine!
