### ISSUE TITLE
curve of h and n in v5.002 regular and light

### ISSUE THREAD

**Issue by d-mal** [JulietaUla/Montserrat#31]
Somehow the curves of h and n in the regular and light weights look thicker than the vertical stems. 
It's a small thing, maybe it's only my impression, but it makes theses shapes top-heavy for me.

**Comment by CaroGiovagnoli** [comment]
Hallo!
Can you send us a screenshot, please?
Danke schön!

**Comment by CaroGiovagnoli** [comment]
@d-mal hi, I think that the problem with the h curves come from the problem with the i-dot in #30
I have resolved the #30, can you see if the curves is ok, if it is not, please send us a screenshot.

**Comment by d-mal** [comment]
I don't know how the internal mechanics work ;) so I can't really guess what the reason was, but yes, you fixed the issue! Thank you!
![montserrat5002a-b](https://cloud.githubusercontent.com/assets/24476952/21958414/dc1953e6-daad-11e6-9cd0-b8d65f2396de.PNG)
The previous version is in grey, and it's quite a bit to thick on top.

**Comment by CaroGiovagnoli** [comment]
fix #31
:)
