### ISSUE TITLE
Bracket Mismatch in Google Fonts

### ISSUE THREAD

**Issue by pabloselin** [JulietaUla/Montserrat#35]
Hi, thanks for your nice Font!

It seems that the last version of the font has a mismatch with the brackets, the {} look like [] and the {} look like []

You can check it easily in the Google Fonts demo:

https://fonts.google.com/specimen/Montserrat

Thanks!!

**Comment by davelab6** [comment]
@pabloselin THANK YOU for reporting this! 

@m4rc1e we need a way to catch stuff like this :)

**Comment by davelab6** [comment]
Google Fonts API version is being rolled back.

**Comment by juandelperal** [comment]
Just checked and in v. 6.0 all seems to be ok
The version available at google is a mix
- 400 and 700: 2.001
- all the other weights: 4.001

**Comment by davelab6** [comment]
@juandelperal you see the mix because of the rollback (which is now complete - so now v4 is removed from the GF servers.) 

Please make a v6.001 release and @m4rc1e will make the GF PR :)

**Comment by pabloselin** [comment]
Thanks so much for the quick fix!!
