### ISSUE TITLE
Montserrat Italic Review

### ISSUE THREAD

**Issue by m4rc1e** [JulietaUla/Montserrat#37]
Hey folks,

Before I can accept v6.001, the following needs to be fixed:

Family:
- Version numbers incremented to 6.001, they're currently 5.000
- delete .null glyph and give NULL unicode 0000
- The following glyphs are present in either the Roman or the Italic but not both:
    eight.lf
    jacute
    zero.lf
    three.lf
    one.lf
    c_t
    Tdieresis
    semicolon.sc
    nine.lf
    idotless.sc
    _temp.tildecomb
    f_f_ij
    quotesinglbase.sc
    two.lf
    ogonekcomb.a.u.alt
    c_h
    Napostrophe
    question.002
    seven.lf
    f_ij
    four.lf
    s_t
    comma.sc
    f_f
    _temp.interpol
    f_f_i
    f_f_l
    colon.sc
    Jacute
    commaaccentcomn
    five.lf
    six.lf
I understand some of these may not be needed in one font or the other. However glyphs like Tdieresis are essential.

Italic:
-nbspace must be same width as space

Roman:
- ss01 glyph count inconsistent with Italic 20+ missing. Is this intentional?

cc @davelab6

**Comment by juandelperal** [comment]
Thanks Marc. I will check the issues. 

> ss01 glyph count inconsistent with Italic 20+ missing. Is this intentional?

Yes, is intentional.

> Version numbers incremented to 6.001, they're currently 5.000

What happened there!? I will take a look. Thanks

**Comment by juandelperal** [comment]
Hi there!

> What happened there!? I will take a look. Thanks

It actually was the 5.000. I made a mistake tagging. Now the issue is fixed and I tagged again in the REAL 6.001.

I cannot assign a unicode to NULL character. In glyph's xml the character name is .null and doesn't have unicode. Please take a look if I have to change anything there.

Thanks again!

**Comment by davelab6** [comment]
@juandelperal can this be closed? :)

**Comment by juandelperal** [comment]
Yes!
