### ISSUE TITLE
Font weights have changed, looks worse

### ISSUE THREAD

**Issue by yougotashovel** [JulietaUla/Montserrat#38]
Have been using this font on a website through Google Fonts.  Looked great, spent a long time choosing it.

Now the weights of the font have changed on the live website and it looks worse, i've tried selecting the original weight but it just doesn't look right anymore.

How do i revert or get a copy of the older version of this font?

**Comment by juandelperal** [comment]
Hi @yougotashovel 
You have the old (deprecated) version here: https://github.com/JulietaUla/Montserrat/releases/tag/v2.001

Cheers

**Comment by tempusrname** [comment]
I have the same complaint. The 'normal' weight of the old version was absolutely perfect. I like the new styles but please bring back the older weight.

Will this be fixed or will it stay like this?
