### ISSUE TITLE
Montserrate Update

### ISSUE THREAD

**Issue by tempusrname** [JulietaUla/Montserrat#39]
I'm not sure if I like the new changes made to Montserrat on google webfonts. https://fonts.google.com/specimen/Montserrat

I love the fact that new styles were added and that Montserrat has grown. What I don't like is that the 'normal' font weight of the previous version is nowhere to be found in the new version. The closest one is 500(Medium), but that one is slightly bolder.

To sum things up: the 400 font weight of the previous version should have been the 500 of this one.

**Comment by yougotashovel** [comment]
Agreed, i added the same issue a few hours ago, was told to check previous versions, but the update to Google Fonts is annoying.  I like using Google Fonts delivery for speed.

**Comment by Samrura** [comment]
Have to agree with both of you the 400 is too think now

**this is how the old 400 looked** 
http://puu.sh/tWcr9/3b1e0eecea.png

**now it looks like this** 
http://puu.sh/tWcsN/de867ac980.png

any chance I can get the old font files and just upload them my self as the google ones aren't up to scratch
love the font by the way , It's better than proxima nova in my opinion.  

_thanks_

**Comment by davelab6** [comment]
I will say that looking at https://fonts.google.com/specimen/Montserrat I think the Regular is much heavier than its italic, which is not good. 

<img width="373" alt="screen shot 2017-02-09 at 18 30 59" src="https://cloud.githubusercontent.com/assets/261579/22811820/00fc50a8-eef6-11e6-93bd-3ca30c8ddde1.png">

**Comment by davelab6** [comment]
> any chance I can get the old font files and just upload them my self as the brick.im/google ones aren't up to scratch

Fonts are living things; which are the 'old' ones that **are** 'up to scratch'? =)

**Comment by rusrus** [comment]
I so liked the "old" 400 Montserrat. Would love to have that back. The new 400 is too faint. The new 500 is too strong.

**Comment by davelab6** [comment]
I hope the monserrat team can explain the reason they reduced the weight of the 400 here :)

**Comment by JulietaUla** [comment]
Hello!

We’ve been working in the last years, with a great team, in the extension of the Montserrat typeface: different languages, quantity of weights and italics.
One of the goals was to achieve an optimum redistribution in 9 weights. The first step was to adjust the weight of the Regular. After several tests we consider that the new one performs better on screen and improves the typographic color program. We have Regular and Medium now.

Google Fonts will only have the latest Montserrat available, but the one who wants to use the previous one is free to download it and use it self-hosted with @ font-face (it does not count with the advances of languages, weights and italics).

**Comment by juandelperal** [comment]
@davelab6 are you sure you don't have an old version installed in your system?
Here it's what I see:
![mont](https://cloud.githubusercontent.com/assets/2414972/22857642/74402d72-f087-11e6-9259-4cbd539c6a17.png)

**Comment by tempusrname** [comment]
@JulietaUla Thank you for response. I see your point and would like to make a suggestion. Would it be possible to release the previous version of Montserrat on google webfonts separate from the new one. Sort of like 'Montserrat Legacy' indicating its the older and preferred version for many. If users prefer the old version of Montserrat they can easily use it like before. I know users can download and use the old Montserrat, but that would defeat the purpose of why many go with google webfonts, which is cache, efficiency and simplicity.

**Comment by JulietaUla** [comment]
@tempusrname Thank you!

**Comment by davelab6** [comment]
Maybe the medium could be updated to match the old regular?

**Comment by tempusrname** [comment]
@davelab6 That would also be a good solution.

**Comment by rusrus** [comment]
@JulietaUla @juandelperal

I would like to use the previous Montserrat and self-host it with @ font-face  - 

Where do I download this? 
Is the previous version v2.001? 
Does it contain the .woff2 and .woff formats?

Thank You

**Comment by juandelperal** [comment]
#40 #38 
We added the 1.0 version to the repo.
Please download and self host.
https://github.com/JulietaUla/Montserrat/releases/tag/v1.0

**Comment by DanielMcPhee** [comment]
@juandelperal: the 1.0 repo doesn't appear to include .woff2. Any chance on an update?

**Comment by juandelperal** [comment]
@DanielMcPhee updated!

**Comment by DanielMcPhee** [comment]
@juandelperal thanks!

**Comment by danyj** [comment]
@juandelperal    

> We added the 1.0 version to the repo.

see this please , looks like Google is only presenting v2  on their site but serving  v1  with only 2 font weights 

![screenshot_1](https://cloud.githubusercontent.com/assets/2340172/23129893/ad44a4a0-f784-11e6-8b5d-12922a037d13.jpg)


see this video please ,  the font switch is calling corresponding CSS file but we get to see only 2 font weights.

http://take.ms/lF9FZ

**Comment by davelab6** [comment]
Is it installed locally?

**Comment by danyj** [comment]
@davelab6   yes font was installed cache cleared from all browsers but Chrome was simply not playing along if you using the font  in WordPress and are logged in as admin .

 I was forced to completely clear all Chrome cache. Dev tools cache clear or previous 4/7 days clear did not work.  I see this being an issue for many users. There  should have been  Montserrat v2  to save everyone the trouble.

**Comment by davelab6** [comment]
I understand that you care about this. But of the millions of users only a
few have complained or even commented at all; if there is a huge outcry
with 1,000s of people petitioning me I'd think I made a poor decision. But
I don't see this, so, I think I made the right decision.

**Comment by danyj** [comment]
All in all , thank you for the great font and additional weights!

**Comment by DanielMcPhee** [comment]
>>> I understand that you care about this. But of the millions of users only a
few have complained or even commented at all; if there is a huge outcry
with 1,000s of people petitioning me I'd think I made a poor decision. But
I don't see this, so, I think I made the right decision.

@davelab6 - to be fair, many won't know to complain because they've got the old font versions installed locally.

**Comment by davelab6** [comment]
Their users would complain to them, though, without having the fonts
installed

**Comment by DanielMcPhee** [comment]
> Their users would complain to them, though, without having the fonts
installed
@davelab6 - I'd say their users won't really know the difference though. It doesn't make the font illegible - it makes them different.

**Comment by danyj** [comment]
@davelab6 ,  this is what I am afraid of and would like input on it , 

users have old font installed ,

 I release theme that is using the Google fonts and using 200 and 300 font weights , 

are the users with old font going to get fresh copy pull from Google and see the theme as I intended or are they going  to see the only old 400 and 600 weights until they install new font?

**Comment by danyj** [comment]
@JulietaUla    this is exactly what I was talking about in my previous post

the font new version has been released long time ago ,  on one of my machines I have not unistalled/reinstalled the font and on the other I did 

these are same headings on 2 diff machines with regular weight

![screenshot_15](https://cloud.githubusercontent.com/assets/2340172/25555467/553077c4-2ce7-11e7-86b1-e6b97358cf8f.jpg)


and these are buttons using regular font size and weight
![screenshot_16](https://cloud.githubusercontent.com/assets/2340172/25555475/9d9dc6ec-2ce7-11e7-99c7-3d5040a6d639.jpg)

 , as you can see one is heavier than the other which is making huge difference in design. 


so you are expecting us to tell everyone on the net to uninstall and reinstall old Montserat in order for designers/developers to be able to use all other sizes that you have made. 


You should make v2  because we simply are not able to use any  of the other sizes that you have made because users that have installed or have cached old font version will not see new sizes.

**Comment by juandelperal** [comment]
@danyj Are you using fixed width buttons?
Anyway. The v2 version is here: https://github.com/JulietaUla/Montserrat/releases/tag/v2.001

**Comment by danyj** [comment]
@juandelperal , no ,  they padded
