### ISSUE TITLE
Reconsider size of '%' zeros

### ISSUE THREAD

**Issue by davelab6** [JulietaUla/Montserrat#41]
Per @rgrundig comment in https://github.com/JulietaUla/Montserrat/issues/40#issuecomment-279445170 here is Montserrat vs Exo 2, Roboto, and and Rubik

I think he is probably right that they are too big... certainly in the italic, its very wide

<img width="554" alt="screen shot 2017-02-14 at 11 17 25" src="https://cloud.githubusercontent.com/assets/261579/22937704/593a71b4-f2a7-11e6-9afb-08c8210d63ce.png">
<img width="664" alt="screen shot 2017-02-14 at 11 18 07" src="https://cloud.githubusercontent.com/assets/261579/22937705/593d6c48-f2a7-11e6-8ec9-5a6988f51ae0.png">
<img width="640" alt="screen shot 2017-02-14 at 11 18 17" src="https://cloud.githubusercontent.com/assets/261579/22937707/5943ac7a-f2a7-11e6-8525-32711fccc6cc.png">
<img width="777" alt="screen shot 2017-02-14 at 11 17 15" src="https://cloud.githubusercontent.com/assets/261579/22937706/593e810a-f2a7-11e6-8b3f-2b66103150d4.png">

**Comment by juandelperal** [comment]
Thanks @rgrundig for pointing this and @davelab6 for reopen the issue. We'll fix it

**Comment by juandelperal** [comment]
Thanks @CaroGiovagnoli for fixing this.
https://github.com/JulietaUla/Montserrat/releases/tag/v6.002
