### ISSUE TITLE
Cherokee (osiyo, Tsalagi wado)

### ISSUE THREAD

**Issue by ghost** [JulietaUla/Montserrat#42]
Osiyo Julieta,

Will you add Cherokee (Tsalagi, or ᏣᎳᎩ) to Montserrat?

Cherokee is of interest to Americans with ancestors native to North America. Cherokee, having 84 glyphs is included in every version of Windows and Apple operating systems. Keyboard setup and use in both is a snap. However... designing and building a font is no snap. Neither is Montserrat any Everson Mono, yet. Request.

Wado, Taya'koia Takwah (Mark)

**Comment by davelab6** [comment]
I understand the need for more Cherokee fonts, and while Google Fonts aims long term to provide a collection of fonts for many languages, currently there is no plan to commission support for Cherokee in Montserrat. However, if you would like to organize modest funding for Julieta and the Montserrat team to do this, I expect they would be glad to :)

**Comment by anyotherway** [comment]
Academic only, forte cultural anthopology.
Google is very specific about 'regional limitations', that include avoiding anything but imperialized latin across all lands in today's colonial Americas. However, if Trump could deposit some wall bricks in our bank accounts...

On 2017 Feb 27, at 0119, Dave Crossland <notifications@github.com> wrote:

I understand the need for more Cherokee fonts, and while Google Fonts aims long term to provide a collection of fonts for many languages, currently there is no plan to commission support for Cherokee in Montserrat. However, if you would like to organize modest funding for Julieta and the Montserrat team to do this, I expect they would be glad to :)

**Comment by davelab6** [comment]
Are you familiar with the Noto project? :)

**Comment by JulietaUla** [comment]
The Noto Project, AWESOME!
Congratulations!!!

2017-02-27 8:56 GMT-03:00 Dave Crossland <notifications@github.com>:

**Comment by JulietaUla** [comment]
Of course!
Besos

2017-02-27 6:27 GMT-03:00 Mark <notifications@github.com>:

> Academic only, forte cultural anthopology.
> Google is very specific about 'regional limitations', that include
> avoiding anything but imperialized latin across all lands in today's
> colonial Americas. However, if Trump could deposit some wall bricks in our
> bank accounts...
>

**Comment by anyotherway** [comment]
Noto ? Yes

According to Apple, Google can't work out viewport. So system publish/view Noto : kaboom.

MaxCDN's bootstrapcdn reset might help for some devices...

selector, selector[element="vh,vmin,vw"] { viewport { width: device-width; }
    }
Maybe reset fix but not my issue. Google: "Google is not responsible". We are, lol.

Noto concept (clip type) nice. OS pending.


On 2017 Feb 27, at 0356, Dave Crossland <notifications@github.com> wrote:

Are you familiar with the Noto project? :)
