### ISSUE TITLE
African glyphs

### ISSUE THREAD

**Issue by brawer** [JulietaUla/Montserrat#43]
Hi Julieta, I’ve drawn a couple additional Latin glyphs for Montserrat, used mainly in African languages. In the [attached Glyphs file](https://github.com/JulietaUla/Montserrat/files/841025/Montserrat-African.glyphs.zip), I’ve marked my changes in yellow. Specifically, I added drafts for the following glyphs:

* **Combining marks:** circumflexbelowcomb

* **Uppercase letters:** Acaron, Adieresismacron, Bdotbelow, Bhook, Bstroke, Chook, Dafrican, Dcircumflexbelow, Dhook, Ecedilla, Eopen, Ereversed, Esh, Fhook, Ghook, Ghook.ss01, Hhook, Hturned, Icaron, Lcircumflexbelow, Ncircumflexbelow, Nhookleft, Nhookleft.ss01, Ocaron, Oopen, Phook, Rstroke, Tcircumflexbelow, Thook, Tretroflexhook, Vturned

* **Lowercase letters:** acaron, adieresismacron, bhook, chook, dcircumflexbelow, dhook, dtail, ecedilla, ecircumflexdotbelow, eopen, esh, eturned, eturned.ss01, ghook, hhook, hturned, icaron, istroke, jdotless, khook, lcircumflexbelow, ncircumflexbelow, nhookleft, ocaron, oopen, phook, qhooktail, rfishhook, rhook, tcircumflexbelow, thook, thook.ss01, tretroflexhook, tretroflexhook.ss01, vhook, vturned, whook, wturned, yhook, yhook.ss01

To fully support African languages, one would need to do more work. But before completing it, I wanted to ask if the direction is reasonable. I haven’t done any kerning, but I’ve tried to assign reasonable kerning classes to the new glyphs. Also, I haven’t drawn any small caps glyphs yet — again, I first wanted to get your feedback on the current drafts.

Feel free to incorporate these glyphs into the main Montserrat master, perhaps after tweaking.

**Comment by CaroGiovagnoli** [comment]
Hi!

Good work! :)

I have moved the stem in nhookleft, in master light and black (the original is in mask)
Something happened with the right space in Dhook, I have fixed it.
[Montserrat-African.glyphs 2.zip](https://github.com/JulietaUla/Montserrat/files/845999/Montserrat-African.glyphs.2.zip)

We have moved this down in your archive in black master (and moved up the other below diacritics) so  they are aligned. (png1)
<img width="890" alt="1" src="https://cloud.githubusercontent.com/assets/8618171/23970765/5517d262-09cb-11e7-9fa1-a3d7a294b29a.png">


**Uppercase letters:**
Something happened with the right space of B+diacritic and D+diacritic, I have fixed it.

Is Eopen the same ducuts that E.ss01?

Some glyphs have a ss01 version, you have included a few, all the set is:
A.ss01
E.ss01 > IT IS THE SAME SHAPE AS Eopen.
F.ss01
G.ss01
I.ss01
J.ss01
M.ss01
N.ss01
Eng.ss01
Q.ss01
T.ss01
U.ss01
W.ss01
Y.ss01
Z.ss01

Maybe the stroke in R black is very short and thick, for example, the stroke/bar in t must be almost as thick as the crossbar, therefore it is different than the bar/stroke in h or d, but I don’t know why the thickness in BDR are different. (png 2 and 3)
<img width="1093" alt="2" src="https://cloud.githubusercontent.com/assets/8618171/23970782/640374f2-09cb-11e7-81d7-6d007ebd33d1.png">
<img width="1167" alt="3" src="https://cloud.githubusercontent.com/assets/8618171/23970783/6408c8bc-09cb-11e7-9990-5453c3878e5d.png">


I understand that the hook in CGBDHPT must continue the color of the stem, maybe you can modulate a bit in CG like Ohorn Uhorn (specially in black master) (png 4)
<img width="1251" alt="4" src="https://cloud.githubusercontent.com/assets/8618171/23970791/6c659e72-09cb-11e7-9b81-cc5767ea012f.png">


**Lowercase letters:** 
Some glyphs have a ss01 version, you have included a few, all the set is:

a.ss01
e.ss01
f.ss01
l.ss01
t.ss01
w.ss01
y.ss01
z.ss01

The same happens in chook as in the uppercase
Maybe eopen can be a bit more extended, now it is a bit condensed

Saludos
Caro

**Comment by brawer** [comment]
Thanks for the review! Is it OK if I send you a series of changes similar to https://github.com/JulietaUla/Montserrat/pull/45? (For each change, I’d then make sure that the glyph also is in the italic font). Or would you prefer that I improve my draft and then you’ll do the merging on your side?

**Comment by CaroGiovagnoli** [comment]
We prefer that du improve your draft and then we'll do the merging.
Saludos!

**Comment by brawer** [comment]
Hi Caro, see here for my current version of [Montserrat.glyphs](https://github.com/brawer/Montserrat/raw/master/sources/Montserrat.glyphs) and [Montserrat Italic.glyphs](https://github.com/brawer/Montserrat/raw/master/sources/Montserrat%20italic.glyphs). As you’ll see, I’m still working on it, but perhaps you could start merging in the accents if they’re good. I’ve marked my additions in orange. When I changed an existing glyph (for adding anchors), I’ve marked it in yellow. I’ve been struggling with `alpha-latin` and `eopen`, make sure to inspect those very carefully.

**Comment by CaroGiovagnoli** [comment]
Hi, ok, I'll take a look at your repos. We'd rather merge everything back once you're done with it.
Saludos!

**Comment by brawer** [comment]
@juandelperal, is there anything in my version of [Montserrat.glyphs](https://github.com/brawer/Montserrat/raw/master/sources/Montserrat.glyphs) and [Montserrat Italic.glyphs](https://github.com/brawer/Montserrat/raw/master/sources/Montserrat%20italic.glyphs) that you might want to merge back? Otherwise, I’ll delete my version since I won’t find time to work on it anytime soon. But perhaps you’ll find some parts useful. Thanks for having a look — would be good to resolve this.

**Comment by davelab6** [comment]
Ah, @brawer 's effort has become unsynced, since all latin glyphs have been revised by @fonthausen, and while Caro sent some feedback to @brawer, it is now going to be a little complicated to merge this... I suggest not to delete your version as it may be useful reference material, but I think these glyphs would need to be redone

**Comment by juandelperal** [comment]
Thank you very much @brawer for your help with this.

**Comment by boydkelly** [comment]
Would love to see support for the folowing glyphs.   These provide support for Mande based languages in West Africa such as Bambara and Jula (dioula).   About 30 million speak these languages.  

Glyph IPA | Unicode
-- | --
ɔ | "0254
Ɔ | "0186
ɛ | "025B
Ɛ | "0190
ɲ | "0272
Ɲ | "019D
ŋ | "014B
Ŋ | "014A

Only about 24 of the current Google fonts support these glyphs either very well or partially.   Would be awesome to get Montsarrat added one day!   

https://www.coastsystems.net/en/post/fontlist/

**Comment by brawer** [comment]
@solmatas Since you're currently looking at #64 for Navajo (yay! thank you!!), perhaps you could also handle this long-open issue #43 to support African languages? Again, the versions will have diverged too much for direct merging, but perhaps you could pick up the work and paste it via Glyphs. It shouldn't take more than a few minutes of your time.
