### ISSUE TITLE
Add top and bottom anchors to all base glyphs

### ISSUE THREAD

**Issue by brawer** [JulietaUla/Montserrat#44]
Would it make sense to add `top` and `bottom` anchors to all base glyphs? For most glyphs, they are already present, but eg. `b` has no anchors yet. This would make it possible to attach combining marks to any base Latin latin letter.

**Comment by davelab6** [comment]
I agree, id like to see this in all fonts

**Comment by juandelperal** [comment]
I think this is now fixed in the new revision by @fonthausen

**Comment by Fonthausen** [comment]
I only added anchors on base glyphs that are used for the accented glyphs in the GF encoding ! 
Dave might have a point there. Maybe it should be standardized from now on.

**Comment by davelab6** [comment]
Yeah I'd like to see all accents done with mark or mkmk as it reduces
filesize
