### ISSUE TITLE
Question: Support for Latin extended.

### ISSUE THREAD

**Issue by Triloworld** [JulietaUla/Montserrat#46]
What languages it support? Is there Latin Extended. I'm interested in Polish case, where exist some special letters.

What is different than [Google Font](https://fonts.google.com/specimen/Montserrat?selection.family=Montserrat)?

**Comment by CaroGiovagnoli** [comment]
Yes, Montserrat is Latin Extended and supports Polish.
If you see any glyph that needs improvement, let us know and we will try to fix it.

**Comment by davelab6** [comment]
Currently the GF copy matches the latest release of TTF files here (afaik)

**Comment by Triloworld** [comment]
Thank you. That's great! You are awesome!
It will be very helpful if in readme.md ([Instruction](https://guides.github.com/features/mastering-markdown/)) can be added information about supported languages? Less question in future ;) and more people willing to help.

**Comment by davelab6** [comment]
@graphicore is working on a web specimen tools project that will make it automatic to determine what a font family supports.

**Comment by Triloworld** [comment]
Great. So this issue can be closed :) Thank you for all information. It was very helpful ! 👍
