### ISSUE TITLE
Use different Eng for Dinka

### ISSUE THREAD

**Issue by brawer** [JulietaUla/Montserrat#47]
Could you add the following to the `locl` feature of Montserrat?

```
language DNK;
sub Eng by Eng.ss01;
sub eng.sc by eng.sc.ss01;
```

@andjc requested this for Noto Sans in https://github.com/googlei18n/noto-fonts/issues/900, but this equally applies to other fonts such as Montserrat. It would be great to know if this should also be done for [other languages](https://www.microsoft.com/typography/otspec/languagetags.htm) beyond Dinka; perhaps @andjc or @moyogo might know which languages are affected.

**Comment by brawer** [comment]
See also https://github.com/googlei18n/noto-fonts/issues/808#issuecomment-298403290 about Eng (and other letters).

**Comment by andjc** [comment]
@brawer, I haven't looked at Montserrat yet, so not sure if adding DNK language is warranted, it depends on whether Montserrat supports the other characters required by Dinka. 

The initial Noto issue was raised because Noto was claiming to support Dinka.

**Comment by andjc** [comment]
@brawer I just did a test on the font. It doesn't support Dinka, so it would be counter productive to add a `locl` feature for the `DNK ` OT language system. I would suggest closing the issue as wontfix.

**Comment by andjc** [comment]
![montserrat-dinka](https://cloud.githubusercontent.com/assets/1468027/25605254/edea6026-2f4c-11e7-814a-8dff8ba080ce.png)

**Comment by moyogo** [comment]
@andjc See #43 which has a .glyphs file with the letters: Ɛ ɛ Ɔ ɔ. Only the letter Ɣ ɣ is missing.

**Comment by andjc** [comment]
@moyogo well with out Ɣ ɣ it is still unsuitable. Although there are other inherent problems with the font. For some African languages, to access the correct Eng will mean using ss01. But from a cursory glance at the font in the git hub repo, this would cause chaos for lots of African languages. 
Eg E.ss01 E.sc.ss01 and and all the glyphs based on these.

It would make more sense to copy Eng.ss01 and Eng.sc.ss01 to either Eng.ss02 and Eng.sc.ss02 or alternatively use a cvNN feature for them. The glyphs can also remain in ss01 for compatibility but it is inappropriate for African languages to use ss01, the confusion between Open E and E.ss01 is quite problematic.

And we don't really want to introduce the need for character level markup in web pages just to target ss01 support to specific characters.

**Comment by juandelperal** [comment]
Hi!
Thanks for your help :)
We didn't merge yet your https://github.com/brawer/Montserrat but will do once is ready.
I think we could copy `Eng.ss01` to `Eng.loclDNK` and glyphs will make the substitution.
Please let us know and thanks again

j.

**Comment by juandelperal** [comment]
please follow this issue on #43
