### ISSUE TITLE
Website keeps changing

### ISSUE THREAD

**Issue by smitpiet** [JulietaUla/Montserrat#48]
Julieta, you have made a very beautiful font with Montserrat, but you keep changing it at Google fonts, and so my website changes as well. Could you please keep it the way it is so I don't have to fear my website looks different next time? I know there are many more who use your font Montserrat because it looks so great, and they also have this issue. Could you just rather add to it instead of changing? Thank you.
Pieter

**Comment by davelab6** [comment]
I'm responsible for the Google Fonts collection, and I work with designers
like Julieta to make the fonts available from Google Fonts the best they
can be. This requires changes things.

The ofl respects your freedom to self host old buggy copies if​ you wish.

**Comment by JulietaUla** [comment]
:)

2017-05-12 10:09 GMT-03:00 Dave Crossland <notifications@github.com>:

> I'm responsible for the Google Fonts collection, and I work with designers
> like Julieta to make the fonts available from Google Fonts the best they
> can be. This requires changes things.
>
> The ofl respects your freedom to self host old buggy copies if​ you wish.
>

**Comment by MTphilclothier** [comment]
Hi @JulietaUla @davelab6,

Firstly, thanks to Julieta for making such a beautiful font!  It has been a pleasure to work with over the years :)

I also noticed that the fonts seem to have changed significantly at sizes of around 10px.  For example, here's a "before and after" - http://i.imgur.com/QAnea54.png.

I've tested with the latest version of Chrome and Firefox on Windows 8.1 and 10 with varying different DPi screens. The results are the same.

The characters seem to be a lot taller and have less weight in the new version. Is this the new direction for the design?

Thanks!

Phil

**Comment by davelab6** [comment]
> The characters seem to be a lot taller and have less weight in the new version. Is this the new direction for the design?

Yes, this is the latest and best version of the design. You can pick from one of the other weights if you wish, maybe the Medium or SemiBold is now better for you?

**Comment by pipdig** [comment]
@smitpiet @MTphilclothier we had the same issue. Reverting to version 4.001 fixed it for us. Unfortunately the Medium or SemiBold versions did not render well on Windows (as usual for fonts!). Version 4 'Regular' seems to look best across all devices.
