### ISSUE TITLE
Can't print with any OTF iteration of the font

### ISSUE THREAD

**Issue by emirpprime** [JulietaUla/Montserrat#49]
Identical problem to #23, using versions of the font downloaded today.

`ERROR: invalidfont
OFFENDING COMMAND: definefont`

Using the TTF version works fine.

**Comment by davelab6** [comment]
Thanks for reporting! I'm curious, any reason to not use the ttf? :)

**Comment by emirpprime** [comment]
To be honest I'm just picking up the pieces... Font was chosen at by another (boss), and the OTF version is in the "these are the fonts to do presentations in" folder; since he's away I was just looking for a solution for my collegues (which was, "here, install the TTF version"). I don't know if there was a specific reason to choose OTF origionally or not I'm afraid.

**Comment by davelab6** [comment]
@emirpprime thanks for the context. I believe the OTFs now available inside https://github.com/JulietaUla/Montserrat/tree/master/fonts/otf should work without problem. Please let us know :)

**Comment by davelab6** [comment]
I suggest this can be closed

**Comment by WenTsai** [comment]
I had the same issue while using OTFs to print, but TTFs work fine!
