### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by luyatshimbalanga** [JulietaUla/Montserrat#5]
Hello team,
I am a Fedora Project contributor ready to package your fonts. I would like to know what is the current version i.e. 1.0 or 2.1 for example. Thank you,

Luya

**Comment by JulietaUla** [comment]
Thanks Luya
The current version is 3.002.
We will add a changelog file in the next release.
Thanks

**Comment by luyatshimbalanga** [comment]
No problem.

**Comment by graphicore** [comment]
Since 5935083241 the version is 3.100, I suggest to close this issue.
