### ISSUE TITLE
[Cyrillic] missing unicode 02BB

### ISSUE THREAD

**Issue by m4rc1e** [JulietaUla/Montserrat#51]
Before we merge the Cyrillic, I'll be making a few quick reviews.

We're missing unicode [02BB](http://www.fileformat.info/info/unicode/char/02bb/index.htm) from the version which is hosted on Google Fonts.

![screen shot 2017-10-23 at 10 14 03](https://user-images.githubusercontent.com/7525512/31881257-eda72902-b7da-11e7-9ad7-1a9a00e02bd5.png)

**Comment by solmatas** [comment]
Ok, done.

**Comment by moyogo** [comment]
BTW the shapes of 02BB and 02BC are wrong. They should not be straight, in this case they should be similar to 2018 and 2019.
