### ISSUE TITLE
[Cyrillic] Glyph issues

### ISSUE THREAD

**Issue by m4rc1e** [JulietaUla/Montserrat#52]
---
**uni04Be, uni04BF**

Montserrat Cyrillic
![screen shot 2017-10-23 at 10 17 41](https://user-images.githubusercontent.com/7525512/31881470-82d636a8-b7db-11e7-838e-f07ebae569cc.png)
![screen shot 2017-10-23 at 10 23 01](https://user-images.githubusercontent.com/7525512/31881684-2e9cbef8-b7dc-11e7-891e-f3d41c4e0d9e.png)

System font
![screen shot 2017-10-23 at 10 17 48](https://user-images.githubusercontent.com/7525512/31881488-8dbfdb8c-b7db-11e7-834e-00d43fc6b1c8.png)

---
**uni04B0**

Montserrat Cyrillic
![screen shot 2017-10-23 at 10 21 29](https://user-images.githubusercontent.com/7525512/31881615-0334c224-b7dc-11e7-9df6-78d19a378a9e.png)
System font
![screen shot 2017-10-23 at 10 21 36](https://user-images.githubusercontent.com/7525512/31881627-0c5afb34-b7dc-11e7-9fb3-5954e681fd7c.png)

---
**uni20B4**

Montserrat Cyrillic
![screen shot 2017-10-23 at 10 25 44](https://user-images.githubusercontent.com/7525512/31881792-8bb67aac-b7dc-11e7-8bff-308bc18a1ea0.png)

System font
![screen shot 2017-10-23 at 10 24 27](https://user-images.githubusercontent.com/7525512/31881741-5f2cfd94-b7dc-11e7-8d71-6aaa1e802f51.png)
System font

Montserrat's version is more aesthetic but the direction may be wrong?

---
**Other glyph errors**

izhitsa-cy: Contour direction is wrong 
![screen shot 2017-10-23 at 10 36 22](https://user-images.githubusercontent.com/7525512/31882276-20d42746-b7de-11e7-9371-3b1b2b2f676c.png)

MS val report.

![screen shot 2017-10-23 at 10 37 37](https://user-images.githubusercontent.com/7525512/31882308-3f656ddc-b7de-11e7-8374-504b743d58a1.png)

---

review these glyphs across all master please. 

Nice work :-)

**Comment by juandelperal** [comment]
Thanks!

**Comment by solmatas** [comment]
Hi Marc, 
you can look after the Regular. We are still working on the italics.
Thanks!

**Comment by solmatas** [comment]
ѵ --> Done

**Comment by m4rc1e** [comment]
@solmatas unfortunately I have to get another 15 or so Cyrillic fonts proofed and mastered in the next few days. I don't have time to make these alterations myself.

**Comment by solmatas** [comment]
Sorry Marc, may be I was not clear.

I saw that you were pointing some errors from the italic's file.
Because we are working on that file, I was trying to say that it would save time if you only focus on the Regular file for now.
Since the Italics are not ready and you will find many issues until we finish them.
It was not my intension at all to ask you to do the alternations.

**Comment by m4rc1e** [comment]
I see, thank you for explaining.

I'll take another look at the Roman later today. I couldn't find any major issues with it.

**Comment by solmatas** [comment]
Hi Marc, the italics are done! in case you would like to check them. 
Thanks!

**Comment by m4rc1e** [comment]
@solmatas Thank you. These have all been fixed. Will close this.

Great work!
