### ISSUE TITLE
[Cyrillic] Add Cyrillic alt glyphs to Montserrat Alternative family

### ISSUE THREAD

**Issue by m4rc1e** [JulietaUla/Montserrat#53]
In the .glyphs files, we use two customParameters in each instance to do this, *Rename Glyphs*, *Remove Glyphs*.

When the fonts get genned: the rename parameter will do the following:
```
A-cy.ss01 --> A-cy
```

Then A-cy.ss01 gets deleted, thus giving us the alternative family.

I'd like both customParameters updated to include the Cyrillic glyphs

cc @davelab6

**Comment by juandelperal** [comment]
Thanks Marc! Yes, we will add that at the end. 
At the moment we are accessing the alternates with ot ss01

**Comment by davelab6** [comment]
@juandelperal is this done?

**Comment by m4rc1e** [comment]
@juandelperal fabulous! does this mean I can make a pr today?

**Comment by juandelperal** [comment]
Yes :)
Thanks!!

**Comment by solmatas** [comment]
Yes!

**Comment by m4rc1e** [comment]
Excellent news!

I'll start this after lunch. Thank you all for your hard work
