### ISSUE TITLE
[Cyrillic Italic] Issue when generating fonts

### ISSUE THREAD

**Issue by m4rc1e** [JulietaUla/Montserrat#54]
When I generate the fonts, I get this:
![screen shot 2017-10-29 at 14 16 25](https://user-images.githubusercontent.com/7525512/32144664-341bcfb8-bcb4-11e7-817e-e157f9685783.png)

However, It seems fine in the glyphs file:
![screen shot 2017-10-29 at 14 20 02](https://user-images.githubusercontent.com/7525512/32144670-49b1c8f0-bcb4-11e7-9600-454735475318.png)

I'm guessing GlyphsApp may be at fault on this one.

I'm using Glyphs Version 2.4.4 (1075). 

cc @schriftgestalt

**Comment by schriftgestalt** [comment]
How did you export the fonts? What font format? Did you check the "Remove Overlap" box on export?

**Comment by davelab6** [comment]
Georg it seems to me that Glyphsapp should make reproducible builds a
default feature of the app... Eg save the export settings on each export,
and have a File > Re-export option to replay them (maybe only visible when
pressing the alt key?)

**Comment by schriftgestalt** [comment]
There are only those three checkboxes that can vary from one export to the other. 
And all of them can be controlled by custom parameters.

**Comment by schriftgestalt** [comment]
But I could store those settings in the font instead of the user defaults. That might improve this situation a bit.

**Comment by m4rc1e** [comment]
@schriftgestalt apologies for my lack of details. I generated ttfs with the following settings.

![screen shot 2017-10-29 at 18 32 23](https://user-images.githubusercontent.com/7525512/32146996-88643042-bcd7-11e7-8abf-df40dd720681.png)


I've had such cases in the past. My usual solution has been to use the decompose customParameter :-)

**Comment by schriftgestalt** [comment]
I had tried it in Glyphs 2.5. I can reproduce this in 2.4.4. I’ll have a look.

**Comment by davelab6** [comment]
Marc does your GF Glyphsapp checking script set those custom parameters?

**Comment by schriftgestalt** [comment]
The settings where not the problem her. Glyphs didn't correctly decompose the overlapping components. This is fixed in 2.5 already.

**Comment by davelab6** [comment]
@juandelperal I guess to close this, you could add a note to changelog that says which version of Glyphs you used to build with. I made https://github.com/JulietaUla/Montserrat/pull/56/files to make the changelog part of README :)

**Comment by juandelperal** [comment]
Great!
Version 2.4.4 (1075)

**Comment by davelab6** [comment]
When @m4rc1e completes his review today, please update README with a new changelog entry and then make a release on https://github.com/JulietaUla/Montserrat/releases :)
