### ISSUE TITLE
[Cyrillic Alternates] Glyph Errors

### ISSUE THREAD

**Issue by m4rc1e** [JulietaUla/Montserrat#58]
Some little problems remain

![screen shot 2017-10-31 at 16 30 08](https://user-images.githubusercontent.com/7525512/32235993-def5bde0-be58-11e7-93b5-f3d00657d39b.png)
![screen shot 2017-10-31 at 16 29 59](https://user-images.githubusercontent.com/7525512/32235994-df0a5840-be58-11e7-9d01-35049e435d61.png)
![screen shot 2017-10-31 at 16 29 48](https://user-images.githubusercontent.com/7525512/32235996-df208f5c-be58-11e7-8793-aea4076d8401.png)
![screen shot 2017-10-31 at 16 29 44](https://user-images.githubusercontent.com/7525512/32235997-df3d05c4-be58-11e7-9107-f2a17d0530c0.png)
![screen shot 2017-10-31 at 16 29 27](https://user-images.githubusercontent.com/7525512/32235998-df86b1a6-be58-11e7-8b1e-eaed6f60e7ba.png)
![screen shot 2017-10-31 at 16 29 24](https://user-images.githubusercontent.com/7525512/32235999-df9b5e80-be58-11e7-86d1-88c5c52d9086.png)

uni04AD must look like this:
![screen shot 2017-10-31 at 16 31 25](https://user-images.githubusercontent.com/7525512/32236028-f712b6bc-be58-11e7-9da3-5b71bbc801e4.png)

We have this:
![screen shot 2017-10-31 at 16 29 24](https://user-images.githubusercontent.com/7525512/32236035-fc7cbd1e-be58-11e7-9c73-cc6058d43410.png)

**Comment by davelab6** [comment]
For the overlaps I suggest to move the originals to a background layer and manually decompose

**Comment by solmatas** [comment]
@m4rc1e Which file are you checking?
Because on the issue uni04B0 --> we deleted the alternate for that glyph.
uni 04B0 is this:
<img width="661" alt="04b0" src="https://user-images.githubusercontent.com/8105496/32238185-6dea3acc-be67-11e7-81fa-5e40d5eec4cf.png">
and the uni 04AD is this:
<img width="394" alt="04ad" src="https://user-images.githubusercontent.com/8105496/32238217-7fd413f2-be67-11e7-92d4-4441d11433d0.png">

**Comment by m4rc1e** [comment]
When I generate the ttfs from https://github.com/JulietaUla/Montserrat/tree/master/sources

**Comment by davelab6** [comment]
> using Glyphs Version 2.4.4 (1075)

Georg has been clear that he won't fix overlap problems in 2.4 and you need to use 2.5

**Comment by m4rc1e** [comment]
@davelab6 Noted, however, I found 2.5 had several font gen regressions when genning EB Garamond (don't have time to file them yet) and 2.5 is still beta, hence why I try and use 2.4 as much as possible.

**Comment by davelab6** [comment]
Right so then the overlap issues need to be solved by moving the originals to a background layer and manually decomposing them

**Comment by juandelperal** [comment]
It might be a custom parameter replacing problem. We will check. Thanks for pointing this Marc!

**Comment by juandelperal** [comment]
We have resolved this and other alternate problems. There was some missing or problematic (component replacement) in .ss01s:
ÅԮӀҰҮҭЇ **regs**
ÅẏԮԝӚӘӀӏҰҮҭѝЇІйи **italics**

Also we added some missing alternate glyphs for latin and cyrillic.
Thanks for your help!

**Comment by m4rc1e** [comment]
@juandelperal brilliant thanks!

We good for another QA round?

**Comment by m4rc1e** [comment]
Can confirm they've been fixed

![screen shot 2017-11-01 at 10 09 47](https://user-images.githubusercontent.com/7525512/32270206-d2c84f6c-beec-11e7-8f93-18ac830be26b.png)
![screen shot 2017-11-01 at 10 09 32](https://user-images.githubusercontent.com/7525512/32270207-d2dddf4e-beec-11e7-88f8-12f433585bff.png)
![screen shot 2017-11-01 at 10 09 22](https://user-images.githubusercontent.com/7525512/32270208-d2f075c8-beec-11e7-9fec-0055c8621f8c.png)
![screen shot 2017-11-01 at 10 09 04](https://user-images.githubusercontent.com/7525512/32270209-d30ab49c-beec-11e7-99d4-dca60baec874.png)

**Comment by juandelperal** [comment]
Yes! We are ready for a second round. Please let us know than we can add the release in GitHub

**Comment by davelab6** [comment]
This can be closed
