### ISSUE TITLE
Please include appdata in your package

### ISSUE THREAD

**Issue by luyatshimbalanga** [JulietaUla/Montserrat#6]
I created appdata for your typeface according to Appstream guideline: https://freedesktop.org/software/appstream/docs/sect-Metadata-Fonts.html needed for Gnome Software and other appstream applications.

[http://pkgs.fedoraproject.org/cgit/rpms/julietaula-montserrat-fonts.git/tree/julietaula-montserrat.metainfo.xml](url)

Feel free to edit the line like ownership.

Sincerely,

Luya

**Comment by JulietaUla** [comment]
Close issue

**Comment by luyatshimbalanga** [comment]
Done
