### ISSUE TITLE
Is this font no longer web-safe?

### ISSUE THREAD

**Issue by addyannie** [JulietaUla/Montserrat#61]
I have a client that uses Montserrat heavily on their website. The font now isn't displaying correctly and I wondered if this has to do with the updates?

**Comment by nickmacavoy** [comment]
Yes it will do. See the release notes 4 days ago: https://github.com/JulietaUla/Montserrat/releases/tag/v7.200

**Comment by mitheshk** [comment]
Yes its because of the updates, and there have been major updates. If you want you can download older version on local and use it to revert and minimize your re-work.
https://github.com/JulietaUla/Montserrat/releases/tag/v6.002

**Comment by addyannie** [comment]
Thank you all for your help.

I'd like to clarify that the website is not displaying Montserrat at all; it's displaying a serif. The CSS coding given by Google Fonts doesn't seem to be affected by the update, though.

**Comment by davelab6** [comment]
@addyannie can you share the website, or provide a reproduction test page on jsbin.com or similar, and confirm which OS/browser you see this on?

**Comment by addyannie** [comment]
Thanks for all your help. I found the cause of the issue.

**Comment by davelab6** [comment]
I'm curious what that cause was? :)
