### ISSUE TITLE
Improve Vietnamese

### ISSUE THREAD

**Issue by davelab6** [JulietaUla/Montserrat#62]
@crystaltype says the Vietnamese can be improved:

![image19](https://user-images.githubusercontent.com/261579/32696229-62f33a38-c727-11e7-9bef-e4be09ddb53e.png)

- [ ] Grave/acute are tilted too much to the left/right. They should be more uprighted.
- [ ] In the thinner weights, the horn in “ohorn” are not natural. The lower stem should be shorter, to look more like the ones are in the bolder weights.
- [ ] Stacked accents like Breve+accents/ Circumflex+accents are scaled vertically, which made them look thinner/unbalanced. I think we should never scale accents, only resize them but keep the original ratio/weight.
- [ ] The accents in italic weights of ocircumflex are not center aligned.
- [ ] The italic degree of the horn are not matching the italic degree of the overall style.
- [ ] Visible stitch (Also in thin and light weights).

She is willing to help contribute the changes directly, by sending you a 'vietnamese only' glyphapp file for you to review and integrate. 

Or, you can make changes and then push your work to `master` and she will give further feedback :)

**Comment by AlsoScratch** [comment]
@solmatas These are some really good suggestions! I hope you aren't just ignoring them.

**Comment by alerque** [comment]
@AlsoScratch This is the third comment I've seen in the last few minutes bumping issue threads with nothing more than  "me to" or "please respond". Please don't do that, if you want to be notified when issues are addressed you can subscribe to them. In the mean time for most open source and free projects, being poked is not motivational. Also it pokes all the _other_ people that are following along, which is just annoying.

**Comment by JulietaUla** [comment]
This is a bit late, but Jacques le Bailey was working on a new version that was released late 2017 doing design improvements.
