### ISSUE TITLE
Font height/width pattern brakes. Is this a bug?

### ISSUE THREAD

**Issue by danyj** [JulietaUla/Montserrat#63]
In v11 and before  the font size determined when the font is "taller" and when it was stretched, 
On all even **px** font sizes the font was "taller" and on odd it was "wider" 

in v12  this still follows the same pattern but with an issue at font size **25 to 26** ,  they are both wider , thus it trows off the pattern. 

Here is the video showing the issue https://monosnap.com/file/2rGC9SUruTE5eyAtbsBIpCHhOPHrZd

pay attention at the pattern , I start at 20px where the font is "taller",  on 26 this should  still be the case but it changes , it becomes wider and brakes the pattern.

**Comment by danyj** [comment]
Just noticed the old pattern comes back at 40px ,  so from 25 to 40 it is changed

**Comment by davelab6** [comment]
@juandelperal could you take a look at this please? :)

**Comment by juandelperal** [comment]
ç@danyj could you please provide the link and your OS/browser settings?

**Comment by danyj** [comment]
The sites are not live, but you can try here 
https://themezly.com/

this http://prntscr.com/hbn11w  heading is Montserrat

Win 10 
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by juandelperal** [comment]
@danyj I I think this how the hinting works on windows renderer, not a bug. Mac OS Sierra and Chrome Version 62.0.3202.94:
https://www.dropbox.com/s/34gzf3do3i0adld/hint.m4v?dl=0

Please drag and drop the ttf font and send us a full screenshot
from http://testing.huertatipografica.com/ (Hinting section)

![screen shot 2017-11-17 at 8 52 36 am](https://user-images.githubusercontent.com/2414972/32946083-c9c0833c-cb74-11e7-82f2-27f199fed046.png)

**Comment by danyj** [comment]
![screenshot_1](https://user-images.githubusercontent.com/2340172/32946664-bcc19ac6-cb98-11e7-866a-7fe788b0d4a5.jpg)

**Comment by davelab6** [comment]
@juandelperal when I look at @danyj 's screenshot I see that at 11px and 23px, the "O" is circular. But I see that the odd px sizes - 13px, 15px, 17px, 19px, 21px - the "O" looks elliptical in the X dimension - not circular but slightly wider than it is tall. But in the even px sizes - 12px, 14px, 16px, 18px, 20px, 22px - the "O" is more circular in that it is as wide as it is tall. 

Do you see this proportional change?

**Comment by davelab6** [comment]
@lemzwerg could you tell us what is going on here? :)

**Comment by lemzwerg** [comment]
ttfautohint doesn't do anything in the x direction.  However, depending on the pixel size, ttfautohint needs to globally scale glyphs vertically (to align the x height to the grid); this feature, together with grid snapping, can change a round shape to become slightly elliptical, for obvious reasons.

A small change in the font's overall height might be the reason for different behaviour in different font versions.  The x height rounding can also be controlled by ttfautohint parameters – no idea whether the new font version uses changed values...

**Comment by davelab6** [comment]
Right. So, @juandelperal, can you adjust the ttfautohint arguments to get a more circular "O" in more px sizes?

**Comment by juandelperal** [comment]
Sorry guys, maybe I misunderstand the problem, but it is impossible to achieve this.
As you can imagine in a 20px size, the x height isn't 20px tall.
x height is 54% of font size. That's why incrementing the font size by one pixel won't make the x height increase 1 px always, and it will make jumps aprox every 2 px.
(The same happens with caps, height is 70%)
If you don't like the non circular shape of the o in certain size, can you try to adjust the font size with decimals?

**Comment by solmatas** [comment]
Hi!
We are making some tests with @juandelperal
This issue is not a hinting problem. The new o is actually wider than a circle
cc @Fonthausen

<img width="543" alt="screen shot 2017-11-28 at 11 42 41 am" src="https://user-images.githubusercontent.com/8105496/33325799-0e174f46-d432-11e7-9699-fbacd7355393.png">

Some tests can be downloaded from
https://www.dropbox.com/sh/nza3mhffwa6yxz3/AACVqMOck34Kx0_3-Yhxjlypa?dl=1

**Comment by juandelperal** [comment]
I made the tests with ttfautohint, and changing the value (21 in this following example):
`-x 21 -w "" -F 21`

The complete command (to be executed in the ttf folder) is:
`for n in {12..25}; do mkdir $n && for i in $(ls *.ttf); do ttfautohint -x $n -w "" -F $n $i $n/$i; done; done`

The screenshots are taken from Chrome, Windows 7

Please test the files and tell us what do you think

**Comment by Fonthausen** [comment]
Do you have a picture ?

**Comment by juandelperal** [comment]
Yes, in https://www.dropbox.com/sh/nza3mhffwa6yxz3/AACVqMOck34Kx0_3-Yhxjlypa?dl=1

**Comment by Fonthausen** [comment]
I see TTFs and screenshots from yesterday. Sorry for asking, because I don't have a windows machine.

**Comment by juandelperal** [comment]
Hi There!
@davelab6 @Fonthausen @danyj Do we have to leave the hinting settings as they are now or do you have any preference of the tests we made?
Cheers!
