### ISSUE TITLE
Fixed width variant

### ISSUE THREAD

**Issue by tracker1** [JulietaUla/Montserrat#65]
Was wondering if you would consider creating a fixed-width variant?

ratio: 9:16 (width to height)

Would love to use this font in my terminal window.  Though that would also require having the box & line characters rendering appropriately.

**Comment by davelab6** [comment]
Adobe type team a script to generate the box and line glyphs. If you are a
developer you could try to extend the ht letterspacer code to optically
center each glyph in a monospace total width and fully automate the
conversion of any font to monospace

**Comment by CallumCarmicheal** [comment]
I second this. If anyone has created a monospace fork of this - that would be amazing. I would love to use this as my primary font for programming but i require monospaced fonts.

**Comment by magicsoft714** [comment]
Yes, I would be interested in a monospace version of this font as well. I find it very pleasing to look at and easy to read, but I really prefer to code using a monospace font.

**Comment by tracker1** [comment]
@davelab6 I have absolutely have zero experience with any modification or adaptation for typefaces/fonts, or even where to start in terms of tooling or development of them.

**Comment by tracker1** [comment]
@davelab6 if the original font developer wants to suggest a price, I'm happy to contribute... It's poor form to suggest that I should just fork the design and pay someone else to do it.  Beyond this, the tone of your response is a bit off-putting as the suggestion I made was not absurd, or only apply to myself.  It does very little to further discussion, and such suggestions should probably come from the original author, not third party virtue signaling.

**Comment by JulietaUla** [comment]
Sorry guys, we do not have plans to develop a monospace version of this font. 
You should check Toshi Omagari's foundry, Tabular Type Foundry, who is developing only monospace typefaces and they are awesome!
