### ISSUE TITLE
Add image to README

### ISSUE THREAD

**Issue by davelab6** [JulietaUla/Montserrat#68]
It would be nice to have an illustration of the family inline in the README

**Comment by JulietaUla** [comment]
I will prepare it and add to the README.
Thanks, Dave.

**Comment by alerque** [comment]
@JulietaUla I don't see a preview inline in the readme yet ;-) Typically one would leave issues open until they are either fixed (often closing them via the commit itself) or there is discussion indicating that they were rejected as "won't fix" (which doesn't seem to be the case here).
