### ISSUE TITLE
Provide downloadable Archive for TTF/OTF

### ISSUE THREAD

**Issue by tomschr** [JulietaUla/Montserrat#69]
Hi,

this font project is awesome! Great work! :+1: 

Currently, in the [releases section](https://github.com/JulietaUla/Montserrat/releases) you can find the source code as zip or tarball. From a user's perspective, a source code package doesn't make sense. :wink:  It would be nice to offer also an archive with the built TTF or OTF fonts in it.

Another benefit: this makes it easier for packagers of Linux distributions to download the exact version and not to rely on Google Fonts service.

**Comment by juandelperal** [comment]
Wow! Yes, you're right
We will include the files on the next release. There are some minor bugs to
fix.
Thanks

2018-04-10 9:45 GMT-03:00 Andreas Steinel <notifications@github.com>:
