### ISSUE TITLE
Cyrillic with alternates for Bulgarian, Macedonian & Serbian languages

### ISSUE THREAD

**Issue by cssobral2013** [JulietaUla/Montserrat#72]

**Comment by ValentinGenev** [comment]
Good day!
I would like to start with a thank you for the making of this lovely font.

I'm experiencing some complications and I was wondering if you could help me. I'm trying to use the second style set, the one with the slightly rotated "e".

I'm using Google's CDN, the semibold variation in Cyrillic (Bulgarian in particular, I love the "л") and Latin. I tried both:
```
font-feature-settings: "ss01";
font-feature-settings: "salt" 1;
```
but they don't seem to change anything.

I would be very grateful if you could help.

Thanks again and kind regards,
Valentin

**Comment by juandelperal** [comment]
You can do that, but not with Google Fonts.
Instead upload and self host the webfonts in your server
Best!

**Comment by cssobral2013** [comment]
Really, the Version 7.2 has Cyrillic for Serbian Bulgarian and Macedônian
languages. Thank You!

Em seg, 18 de fev de 2019 12:42, Sol Matas <notifications@github.com>
escreveu:
