### ISSUE TITLE
"fr" kerning

### ISSUE THREAD

**Issue by dicario** [JulietaUla/Montserrat#73]
The "fr" pair has an unnaturally huge white space between the two glyphs.
<img width="419" alt="google_fonts_" src="https://user-images.githubusercontent.com/8217264/38636413-c8c45386-3dd0-11e8-8608-cf8b268d7839.png">
.

**Comment by maxfleit** [comment]
Would also like to see a solution to this problem. Look especially akward on bold fonts.

**Comment by StephenSheehan** [comment]
![screenshot 151](https://user-images.githubusercontent.com/22824626/42645225-72072006-85f5-11e8-94e3-43ee02d843e4.png)
Also "fi", which is wrong (and visually identical) whether ligatures are used or not.

**Comment by solmatas** [comment]
Hello,

Thank you for giving us notice about this error.
I uploaded in Github the exported files (ttf, otf and webfonts) with the fixed pairs of kernings.
May be @dave can push this in fonts.google.com

Thanks,
Sol
