### ISSUE TITLE
Cannot print with any version

### ISSUE THREAD

**Issue by mah2g** [JulietaUla/Montserrat#78]
When I try to print using the OTF I get an error saying invalid font. I uninstalled this then tried to print with the TTF and while it technically prints it's garbled and doesn't resemble the intended design. 

This may be user error so I tried uninstalling everything then syncing using Adobe Typekit and got the invalid font error again. 

Any help is greatly appreciated.

**Comment by juandelperal** [comment]
It's been a really long time of this issue, and we didn't answer. 
Sorry for that
We guess this issue is sorted already, so we are closing it now. But If you still has problems, please let us know which OS and software your are running.
