### ISSUE TITLE
Latvian kcommaaccent (ķ) Accent Positioning

### ISSUE THREAD

**Issue by kalapi** [JulietaUla/Montserrat#8]
Hello! Ideally the 'comma below' is aligned to the centre of the lowercase 'k' as seen in the following image:
![kcommaccent](https://cloud.githubusercontent.com/assets/15804460/14363291/1c9be99e-fd21-11e5-8709-87bae14620fe.jpg)
(Typefaces from the left: Source Sans Pro, Constantia, Droid Serif, Gentium, Lucida Sans, Palatino Linotype, and Roboto. Images courtesy www.fileformat.info)
However, in Montserrat, the 'comma below' is centered below the stem of the 'k' instead of being centered below the entire letter;
![screen shot 2016-04-08 at 00 26 41](https://cloud.githubusercontent.com/assets/15804460/14363354/641e21d8-fd21-11e5-89e5-332b93b71c2c.png)

**Comment by JulietaUla** [comment]
Fixed! Thanks
