### ISSUE TITLE
Error when printing documents containing .OTF variant to PostScript printer .TTF works 

### ISSUE THREAD

**Issue by RWBudd** [JulietaUla/Montserrat#83]
Printing to several different Xerox printers results in a PostScript error if the the .otf font is used in certain applications.  Issue occurs on Mac OS (v10.12,10.13 & 10.14)  & Windows 10 when using current postscript drivers provided by Xerox, Fiery or using the Apple Generic PS driver or Generic Windows PS driver.

Postscript error is:

--------------------

ERROR: invalidfont
OFFENDING COMMAND: definefont

STACK:

/Font
-dictionary-
/WZZCNT+Montserrat-Light

-----------------------
This last line changes based on the variation of the font used (eg light, regular etc).  Other codes seen are:

/DXRNSV+MontserratAlternates-Regular
/SXICWN+Montserrat-Regular
/TEONTZ+Montserrat-Medium
/UQXSDS+Montserrat-Regular

The error does not occur when printing from Adobe Creative Suite Apps.  Printing from Mail, MS Word or TextEdit on Mac OS fails in every case, as does notepad and MS Word on Windows 10.

Removing the .OTF font from the computer and replacing with the .TTF variant fixes the issue in all cases.  No issue observed using other .OTF fonts on any of these systems.

**Comment by JulietaUla** [comment]
Closed #83
