### ISSUE TITLE
Font is not smooth on FIrefox

### ISSUE THREAD

**Issue by lovep34** [JulietaUla/Montserrat#86]
It is showing little bit bolder in Firefox, In chrome it is working fine. I am attaching the shot.

![image](https://user-images.githubusercontent.com/41196164/50399111-0cf5a680-07a3-11e9-8bec-5a4ec2102456.png)

FYI I am using latest versions of both browsers

Thanks in Advance

**Comment by JulietaUla** [comment]
We can see the difference but we can not change how the different browsers are showing the font :(
