### ISSUE TITLE
17px/72DPI on OSX gets chopped on capital letters and ascendents

### ISSUE THREAD

**Issue by rafzan** [JulietaUla/Montserrat#90]
Tested on multiple machines with the same setup. Tried exporting with 72dpi on Retina screen and got same results. It looks really bad on projects. 

Specimen:
![Screen Shot 2019-08-07 at 19 09 48](https://user-images.githubusercontent.com/232089/62661492-9c715380-b947-11e9-9055-8f3dbe979db2.png)

**Comment by karlrudd** [comment]
Note: In your image the font size is 17px, not 16px.

It appears only the weights from Semi-Bold up to Black are having problems. Possibly something to do with the hinting?

One workaround I've found is to slightly adjust the font size. In this case you can change the font size from 17px to 17.01px and it looks much better. (See attached.)

![Montserrat - Google Fonts - macOS 10 14 - Chrome 76](https://user-images.githubusercontent.com/1418080/62679149-ed8c5080-b9f6-11e9-90cb-9ecb35451fe9.png)

**Comment by rafzan** [comment]
Thanks, it worked perfectly!

**Comment by rafzan** [comment]
Update: 

This is a not a problem with Montserrat. It happens with multiple fonts on macOS Mojave on 72dpi screens, on specific sizes.
