### ISSUE TITLE
Latest commit as new version

### ISSUE THREAD

**Issue by Some1NamedNate** [JulietaUla/Montserrat#91]
I propose that https://github.com/JulietaUla/Montserrat/commit/49e9a093314a504e85cd80ecfd7a4bc4b5aa50b5 should be part of version 7.201.

**Comment by AlsoScratch** [comment]
I think this new version should also fix #79 as well.

**Comment by Some1NamedNate** [comment]
@JulietaUla ☝

**Comment by juandelperal** [comment]
Hi!
Thanks for the reminder. Just added
https://github.com/JulietaUla/Montserrat/releases/tag/v7.210
