### ISSUE TITLE
(Request) Separate stylistic set for the lowercase L's

### ISSUE THREAD

**Issue by AlsoScratch** [JulietaUla/Montserrat#92]
I like the alternate lowercase `l`'s (including `l`, `ł`, `ļ`, `ľ`, etc.) having a little bend to the right, but I don't want to affect the other glyphs at the same time. Perhaps the alternate `l`'s could be its own set.

I'm more partial to the bent minuscule `l`'s being the default style, but I'm not sure if you're on board that idea.

**Comment by JulietaUla** [comment]
The alternate 'l' was designed to be part of the alternate Stylistic set.
We like to keep the straight stem 'l' in the original set.
