### ISSUE TITLE
Variable Font Version

### ISSUE THREAD

**Issue by jhned** [JulietaUla/Montserrat#93]
Hey there, just checking: is there a plan to create a variable font version of Montserrat, or does a variable font version already exist?

**Comment by Some1NamedNate** [comment]
Though I agree, there seems to be no variable version of Montserrat in this repo as of now.

**Comment by AlsoScratch** [comment]
@JulietaUla @solmatas Please give _some_ acknowledgement.

**Comment by solmatas** [comment]
Hi everyone! We have the plan of developing a VF of Montserrat! but we don't know yet when this will be happening. We'll keep you updated. =)
@davelab6

**Comment by Some1NamedNate** [comment]
@solmatas How about #91 ?

**Comment by solmatas** [comment]
> @solmatas How about #91? I would scrutinize and resolve any/all kern pairs.

The pairs /fr/ and /fi/ were solved last February. You can see that in the last commits. But the font is not updated in the Google directory. That does NOT depends on us (type designers). =(

Of course if you like to collaborate and scrutinize all the kern pairs you can do it. In the case that you find another pair of kerning issue, please let us know. @Fonthausen @juandelperal @JulietaUla 

If you find ay issue referred to the Cyrillic you can refer me or @juandelperal.

Thanks for your feedback.

**Comment by juandelperal** [comment]
Yes! We are working on that, keep posted :)

**Comment by alerque** [comment]
See #95 and PR #96 for the background and status of the variable font version.
