### ISSUE TITLE
Variable font in Windows FontViewer

### ISSUE THREAD

**Issue by jenskutilek** [JulietaUla/Montserrat#98]
Maybe this belongs to the variable fonts fork, but no issues can be filed there, so I'll try here.

When previewing the variable font in Windows 10 (plain FontViewer, just double-click the font), and stepping through the instances, the glyph widths don't change as the weight progresses. This leads to overlapping glyphs in the heaviest weights. Is this just a Windows bug, or can the font be tweaked to avoid this?

![Bildschirmfoto 2019-12-13 um 11 52 27](https://user-images.githubusercontent.com/3185950/70795254-af85ab80-1d9f-11ea-9938-e9b0cdb428c4.png)

**Comment by Measureless** [comment]
> variable fonts fork

May I ask which fork is it? I want to have a try.

**Comment by alerque** [comment]
@Measureless See #96.

@jenskutilek Have you tried it yourself in some other program? This is likely a bug in the font previewer, but you'll know pretty quickly if you check that the font actually works in things with proper variable support.

**Comment by jenskutilek** [comment]
Yes, indeed it is only the font viewer that shows the font this way. Using it in Word, everything is OK.

**Comment by alerque** [comment]
I don't know if MS has a public facing bug tracker for this kind of thing, but this is not an issue on the font itself. This issue can be closed.
