### ISSUE TITLE
FontStyle italic display another "a"

### ISSUE THREAD

**Issue by kitfall** [JulietaUla/Montserrat#99]
When I using the Montserrat font in the fontstyle italic (in all font weights), the font seems to missing the **a** character and replaces by the system font.
Can you looking where the error can be?

![image](https://user-images.githubusercontent.com/53250303/72424807-dbbd8f00-3786-11ea-9be0-f2c1603acdd2.png)

**Comment by solmatas** [comment]
Hi @kitfall, 
the a is not missing. That is the correct italic version and it is not a slanted style.
Here is a screenshoot of the italic a and the alternate italic:
<img width="1134" alt="a" src="https://user-images.githubusercontent.com/8105496/72430336-5dff8080-3792-11ea-89dc-9fa9ab158c68.png">
